/**
 * 単語データ（TOEIC頻出単語）。例文はオリジナル。
 *   level/phrase/emoji/meaning/example/exampleJa を持つ。
 *   example は phrase を必ずそのまま含む（穴埋め用）。
 */
const IDIOMS = [
  { level: "toeic1", phrase: "anyway", emoji: "🤷", meaning: "いずれにせよ", example: "Anyway, let's continue.", exampleJa: "いずれにせよ、続けよう。" },
  { level: "toeic1", phrase: "following", emoji: "⏭️", meaning: "次の、以下の", example: "Read the following notice.", exampleJa: "以下のお知らせを読んで。" },
  { level: "toeic1", phrase: "refer", emoji: "👉", meaning: "参照する、言及する", example: "Please refer to the manual.", exampleJa: "説明書を参照してください。" },
  { level: "toeic1", phrase: "available", emoji: "✅", meaning: "利用できる、手が空いて", example: "The room is available now.", exampleJa: "その部屋は今利用できる。" },
  { level: "toeic1", phrase: "department", emoji: "🏢", meaning: "部署", example: "She works in the sales department.", exampleJa: "彼女は営業部で働いている。" },
  { level: "toeic1", phrase: "conference", emoji: "🏟️", meaning: "会議、学会", example: "Attend the conference next week.", exampleJa: "来週その会議に出席して。" },
  { level: "toeic1", phrase: "likely", emoji: "📊", meaning: "ありそうな", example: "A delay is likely.", exampleJa: "遅れがありそうだ。" },
  { level: "toeic1", phrase: "offer", emoji: "🤲", meaning: "申し出る、提供", example: "They offer free shipping.", exampleJa: "彼らは送料無料を提供する。" },
  { level: "toeic1", phrase: "equipment", emoji: "🧰", meaning: "設備、機器", example: "The equipment is new.", exampleJa: "その設備は新しい。" },
  { level: "toeic1", phrase: "provide", emoji: "🎁", meaning: "提供する", example: "We provide free coffee.", exampleJa: "私たちは無料のコーヒーを提供する。" },
  { level: "toeic1", phrase: "local", emoji: "📍", meaning: "地元の", example: "Support your local shop.", exampleJa: "地元の店を応援して。" },
  { level: "toeic1", phrase: "purchase", emoji: "🛒", meaning: "購入する", example: "I want to purchase a laptop.", exampleJa: "ノートパソコンを購入したい。" },
  { level: "toeic1", phrase: "opening", emoji: "🚪", meaning: "開店、（職の）空き", example: "There is a job opening.", exampleJa: "求人の空きがある。" },
  { level: "toeic1", phrase: "construction", emoji: "🏗️", meaning: "建設、工事", example: "The construction will finish soon.", exampleJa: "その工事はまもなく終わる。" },
  { level: "toeic1", phrase: "tour", emoji: "🚌", meaning: "見学、ツアー", example: "We took a factory tour.", exampleJa: "私たちは工場見学をした。" },
  { level: "toeic1", phrase: "research", emoji: "🔬", meaning: "研究、調査", example: "She does market research.", exampleJa: "彼女は市場調査をする。" },
  { level: "toeic1", phrase: "attend", emoji: "🙋", meaning: "出席する", example: "I will attend the meeting.", exampleJa: "私はその会議に出席します。" },
  { level: "toeic1", phrase: "delivery", emoji: "🚚", meaning: "配達", example: "The delivery arrived today.", exampleJa: "配達物が今日届いた。" },
  { level: "toeic1", phrase: "recently", emoji: "🆕", meaning: "最近", example: "We recently moved offices.", exampleJa: "私たちは最近オフィスを移した。", accept: ["these days", "nowadays"] },
  { level: "toeic1", phrase: "indicate", emoji: "👆", meaning: "示す", example: "The sign indicates the exit.", exampleJa: "その表示は出口を示している。", accept: ["point out"] },
  { level: "toeic1", phrase: "employee", emoji: "👔", meaning: "従業員", example: "The employee works hard.", exampleJa: "その従業員は熱心に働く。" },
  { level: "toeic1", phrase: "additional", emoji: "➕", meaning: "追加の", example: "There is an additional fee.", exampleJa: "追加料金がかかる。" },
  { level: "toeic1", phrase: "survey", emoji: "📋", meaning: "調査、アンケート", example: "Please complete the survey.", exampleJa: "アンケートに回答してください。" },
  { level: "toeic1", phrase: "review", emoji: "🔎", meaning: "見直す、批評", example: "Review the document.", exampleJa: "書類を見直して。" },
  { level: "toeic1", phrase: "production", emoji: "🏭", meaning: "生産", example: "Production starts in May.", exampleJa: "生産は5月に始まる。" },
  { level: "toeic1", phrase: "located", emoji: "🗺️", meaning: "位置する", example: "The office is located downtown.", exampleJa: "オフィスは中心街にある。" },
  { level: "toeic1", phrase: "detail", emoji: "🔍", meaning: "詳細", example: "Explain every detail.", exampleJa: "細部まで説明して。" },
  { level: "toeic1", phrase: "announce", emoji: "📣", meaning: "発表する", example: "They will announce the results.", exampleJa: "彼らは結果を発表する。" },
  { level: "toeic1", phrase: "repair", emoji: "🛠️", meaning: "修理する", example: "We repair old machines.", exampleJa: "私たちは古い機械を修理する。" },
  { level: "toeic1", phrase: "increase", emoji: "📈", meaning: "増やす、増加", example: "Sales increase every year.", exampleJa: "売上は毎年増える。" },
  { level: "toeic1", phrase: "include", emoji: "🧩", meaning: "含む", example: "Please include your name.", exampleJa: "あなたの名前を含めてください。" },
  { level: "toeic1", phrase: "currently", emoji: "🔆", meaning: "現在", example: "He is currently away.", exampleJa: "彼は現在不在です。" },
  { level: "toeic1", phrase: "advertising", emoji: "📺", meaning: "広告、宣伝", example: "The advertising was effective.", exampleJa: "その広告は効果的だった。" },
  { level: "toeic1", phrase: "charge", emoji: "💳", meaning: "料金、請求する", example: "There is no charge.", exampleJa: "料金はかかりません。" },
  { level: "toeic1", phrase: "expect", emoji: "🔮", meaning: "予期する", example: "We expect good results.", exampleJa: "良い結果を期待している。" },
  { level: "toeic1", phrase: "firm", emoji: "🏢", meaning: "会社", example: "She works at a law firm.", exampleJa: "彼女は法律事務所で働く。" },
  { level: "toeic1", phrase: "client", emoji: "🧑‍💼", meaning: "顧客、依頼人", example: "The client is satisfied.", exampleJa: "その顧客は満足している。" },
  { level: "toeic1", phrase: "financial", emoji: "💹", meaning: "財務の、金融の", example: "We made a financial plan.", exampleJa: "私たちは財務計画を立てた。" },
  { level: "toeic1", phrase: "annual", emoji: "🗓️", meaning: "年次の", example: "We hold an annual event.", exampleJa: "私たちは年次行事を開く。" },
  { level: "toeic1", phrase: "based", emoji: "📌", meaning: "拠点を置く、〜に基づく", example: "The company is based in Osaka.", exampleJa: "その会社は大阪に拠点を置く。" },
  { level: "toeic1", phrase: "facility", emoji: "🏟️", meaning: "施設", example: "The facility is modern.", exampleJa: "その施設は近代的だ。" },
  { level: "toeic1", phrase: "advance", emoji: "⏩", meaning: "前進、事前の", example: "We need advance notice.", exampleJa: "事前の通知が必要だ。" },
  { level: "toeic1", phrase: "committee", emoji: "👥", meaning: "委員会", example: "The committee will decide.", exampleJa: "委員会が決定する。" },
  { level: "toeic1", phrase: "successful", emoji: "🏆", meaning: "成功した", example: "The launch was successful.", exampleJa: "その発売は成功した。" },
  { level: "toeic1", phrase: "excellent", emoji: "🌟", meaning: "優れた", example: "The service is excellent.", exampleJa: "そのサービスは素晴らしい。" },
  { level: "toeic1", phrase: "industry", emoji: "🏗️", meaning: "産業、業界", example: "The tech industry grows fast.", exampleJa: "テック業界は急成長している。" },
  { level: "toeic1", phrase: "fee", emoji: "🪙", meaning: "料金", example: "There is a small fee.", exampleJa: "わずかな料金がかかる。" },
  { level: "toeic1", phrase: "accept", emoji: "🤝", meaning: "受け入れる", example: "Please accept our offer.", exampleJa: "私たちの申し出を受け入れてください。" },
  { level: "toeic1", phrase: "upcoming", emoji: "🔜", meaning: "来たる、今度の", example: "Check the upcoming events.", exampleJa: "今度のイベントを確認して。" },
  { level: "toeic1", phrase: "display", emoji: "🖼️", meaning: "展示、表示する", example: "The store has a nice display.", exampleJa: "その店は素敵な陳列をしている。" },
  { level: "toeic1", phrase: "candidate", emoji: "🧑", meaning: "候補者", example: "She is a strong candidate.", exampleJa: "彼女は有力な候補者だ。" },
  { level: "toeic1", phrase: "state", emoji: "🗣️", meaning: "述べる、状態", example: "Please state your name.", exampleJa: "お名前を述べてください。" },
  { level: "toeic1", phrase: "exhibit", emoji: "🖼️", meaning: "展示する、展示品", example: "The museum will exhibit art.", exampleJa: "その美術館は芸術を展示する。" },
  { level: "toeic1", phrase: "session", emoji: "🕘", meaning: "会、（活動の）時間", example: "The session starts soon.", exampleJa: "その会はまもなく始まる。" },
  { level: "toeic1", phrase: "note", emoji: "🗒️", meaning: "注意する、メモ", example: "Please note the change.", exampleJa: "その変更にご注意ください。" },
  { level: "toeic1", phrase: "process", emoji: "⚙️", meaning: "処理する、過程", example: "We process orders daily.", exampleJa: "私たちは毎日注文を処理する。" },
  { level: "toeic1", phrase: "instruction", emoji: "📜", meaning: "指示、説明", example: "Follow the instruction carefully.", exampleJa: "指示に注意して従って。" },
  { level: "toeic1", phrase: "membership", emoji: "🎫", meaning: "会員資格", example: "Renew your membership.", exampleJa: "会員資格を更新して。" },
  { level: "toeic1", phrase: "agency", emoji: "🏢", meaning: "代理店", example: "We booked through a travel agency.", exampleJa: "私たちは旅行代理店で予約した。" },
  { level: "toeic1", phrase: "payment", emoji: "💳", meaning: "支払い", example: "Payment is due today.", exampleJa: "支払いは本日が期限だ。" },
  { level: "toeic1", phrase: "budget", emoji: "💰", meaning: "予算", example: "We planned the budget.", exampleJa: "私たちは予算を立てた。" },
  { level: "toeic1", phrase: "application", emoji: "📝", meaning: "申込、応用、アプリ", example: "Submit your application.", exampleJa: "申込書を提出して。" },
  { level: "toeic1", phrase: "contract", emoji: "📜", meaning: "契約", example: "Sign the contract here.", exampleJa: "ここで契約に署名して。" },
  { level: "toeic1", phrase: "management", emoji: "🧭", meaning: "経営、管理", example: "The management approved it.", exampleJa: "経営陣はそれを承認した。" },
  { level: "toeic1", phrase: "performance", emoji: "📊", meaning: "業績、性能、公演", example: "The team's performance improved.", exampleJa: "チームの業績が向上した。" },
  { level: "toeic1", phrase: "pleased", emoji: "😊", meaning: "喜んで", example: "We are pleased to help.", exampleJa: "喜んでお手伝いします。" },
  { level: "toeic1", phrase: "confirm", emoji: "☑️", meaning: "確認する", example: "I will confirm the booking.", exampleJa: "予約を確認します。" },
  { level: "toeic1", phrase: "award", emoji: "🏅", meaning: "賞", example: "She won an award.", exampleJa: "彼女は賞を取った。" },
  { level: "toeic1", phrase: "clothing", emoji: "👕", meaning: "衣類", example: "The store sells clothing.", exampleJa: "その店は衣類を売る。" },
  { level: "toeic1", phrase: "warranty", emoji: "🛡️", meaning: "保証", example: "The phone has a warranty.", exampleJa: "その電話には保証がある。" },
  { level: "toeic1", phrase: "necessary", emoji: "❗", meaning: "必要な", example: "Bring the necessary documents.", exampleJa: "必要な書類を持ってきて。" },
  { level: "toeic1", phrase: "reserve", emoji: "📕", meaning: "予約する、取っておく", example: "I want to reserve a table.", exampleJa: "席を予約したい。" },
  { level: "toeic1", phrase: "resident", emoji: "🏘️", meaning: "住民", example: "Every resident got a notice.", exampleJa: "全住民がお知らせを受け取った。" },
  { level: "toeic1", phrase: "create", emoji: "🎨", meaning: "作り出す", example: "We create new designs.", exampleJa: "私たちは新しいデザインを作る。" },
  { level: "toeic1", phrase: "inform", emoji: "ℹ️", meaning: "知らせる", example: "Inform the manager.", exampleJa: "部長に知らせて。" },
  { level: "toeic1", phrase: "allow", emoji: "✔️", meaning: "許す", example: "We allow remote work.", exampleJa: "私たちは在宅勤務を許可している。" },
  { level: "toeic1", phrase: "mention", emoji: "💬", meaning: "言及する", example: "He did not mention the price.", exampleJa: "彼は価格に触れなかった。", accept: ["bring up", "raise"] },
  { level: "toeic1", phrase: "appreciate", emoji: "🙏", meaning: "感謝する", example: "I appreciate your help.", exampleJa: "ご助力に感謝します。" },
  { level: "toeic1", phrase: "replacement", emoji: "🔧", meaning: "交換（品）、後任", example: "We sent a replacement.", exampleJa: "私たちは交換品を送った。" },
  { level: "toeic1", phrase: "policy", emoji: "📋", meaning: "方針、保険証券", example: "Read the company policy.", exampleJa: "会社の方針を読んで。" },
  { level: "toeic1", phrase: "register", emoji: "📝", meaning: "登録する", example: "Register for the event.", exampleJa: "イベントに登録して。" },
  { level: "toeic1", phrase: "arrange", emoji: "🗂️", meaning: "手配する、整える", example: "Please arrange a meeting.", exampleJa: "会議を手配してください。" },
  { level: "toeic1", phrase: "bill", emoji: "🧾", meaning: "請求書、紙幣", example: "Pay the bill, please.", exampleJa: "請求書を支払ってください。" },
  { level: "toeic1", phrase: "hire", emoji: "🤝", meaning: "雇う", example: "We will hire two people.", exampleJa: "私たちは2人を雇う。" },
  { level: "toeic1", phrase: "approve", emoji: "👍", meaning: "承認する", example: "The manager will approve it.", exampleJa: "部長がそれを承認する。" },
  { level: "toeic1", phrase: "conduct", emoji: "🧪", meaning: "行う、実施する", example: "We conduct a survey.", exampleJa: "私たちは調査を行う。" },
  { level: "toeic1", phrase: "opportunity", emoji: "🚪", meaning: "機会", example: "It is a great opportunity.", exampleJa: "それは絶好の機会だ。" },
  { level: "toeic1", phrase: "deadline", emoji: "⏰", meaning: "締め切り", example: "We met the deadline.", exampleJa: "私たちは締め切りに間に合った。" },
  { level: "toeic1", phrase: "corporate", emoji: "🏢", meaning: "企業の", example: "The corporate office is large.", exampleJa: "その本社は大きい。" },
  { level: "toeic1", phrase: "latest", emoji: "🆕", meaning: "最新の", example: "Check the latest update.", exampleJa: "最新の更新を確認して。" },
  { level: "toeic1", phrase: "submit", emoji: "📤", meaning: "提出する", example: "Submit the report by noon.", exampleJa: "正午までに報告書を提出して。", accept: ["hand in", "turn in"] },
  { level: "toeic1", phrase: "transportation", emoji: "🚆", meaning: "交通機関、輸送", example: "Public transportation is cheap.", exampleJa: "公共交通機関は安い。" },
  { level: "toeic1", phrase: "resume", emoji: "📄", meaning: "履歴書", example: "Please attach your resume.", exampleJa: "履歴書を添付してください。" },
  { level: "toeic1", phrase: "executive", emoji: "🤵", meaning: "重役、幹部", example: "The executive made a speech.", exampleJa: "その重役は演説をした。" },
  { level: "toeic1", phrase: "introduce", emoji: "👋", meaning: "紹介する、導入する", example: "Introduce the new plan.", exampleJa: "新しい計画を紹介して。" },
  { level: "toeic1", phrase: "previous", emoji: "⏮️", meaning: "前の", example: "See the previous email.", exampleJa: "前のメールを見て。" },
  { level: "toeic1", phrase: "proposal", emoji: "📃", meaning: "提案", example: "We sent a proposal.", exampleJa: "私たちは提案書を送った。" },
  { level: "toeic1", phrase: "supply", emoji: "📦", meaning: "供給、備品", example: "We have enough supply.", exampleJa: "十分な供給がある。" },
  { level: "toeic1", phrase: "enclose", emoji: "✉️", meaning: "同封する", example: "I enclose a copy.", exampleJa: "写しを同封します。" },
  { level: "toeic1", phrase: "temporary", emoji: "⏳", meaning: "一時的な", example: "It is a temporary fix.", exampleJa: "それは一時的な対処だ。" },
  { level: "toeic1", phrase: "traditional", emoji: "🎎", meaning: "伝統的な", example: "We held a traditional event.", exampleJa: "私たちは伝統的な行事を開いた。" },
  { level: "toeic1", phrase: "admission", emoji: "🎟️", meaning: "入場、入学", example: "Admission is free.", exampleJa: "入場は無料だ。" },
  { level: "toeic1", phrase: "fit", emoji: "👕", meaning: "合う、ぴったり", example: "The shirt is a good fit.", exampleJa: "そのシャツはぴったりだ。" },
  { level: "toeic1", phrase: "reference", emoji: "📚", meaning: "参照、推薦状", example: "Keep this for reference.", exampleJa: "参照用にこれを保管して。" },
  { level: "toeic1", phrase: "status", emoji: "📍", meaning: "状態、地位", example: "Check the order status.", exampleJa: "注文の状況を確認して。" },
  { level: "toeic1", phrase: "fuel", emoji: "⛽", meaning: "燃料", example: "The truck needs fuel.", exampleJa: "そのトラックは燃料が必要だ。" },
  { level: "toeic1", phrase: "nearly", emoji: "📏", meaning: "ほとんど", example: "It is nearly done.", exampleJa: "それはほぼ完了だ。" },
  { level: "toeic1", phrase: "cafeteria", emoji: "🍽️", meaning: "食堂", example: "Lunch is in the cafeteria.", exampleJa: "昼食は食堂でとる。" },
  { level: "toeic1", phrase: "determine", emoji: "🧭", meaning: "決定する、特定する", example: "We will determine the date.", exampleJa: "私たちが日付を決める。" },
  { level: "toeic1", phrase: "correct", emoji: "✔️", meaning: "正しい、訂正する", example: "The answer is correct.", exampleJa: "その答えは正しい。" },
  { level: "toeic1", phrase: "downtown", emoji: "🏙️", meaning: "中心街（で）", example: "The hotel is downtown.", exampleJa: "そのホテルは中心街にある。" },
  { level: "toeic1", phrase: "method", emoji: "🛠️", meaning: "方法", example: "It is an effective method.", exampleJa: "それは効果的な方法だ。" },
  { level: "toeic1", phrase: "entire", emoji: "🟦", meaning: "全体の", example: "The entire team agreed.", exampleJa: "チーム全体が賛成した。" },
  { level: "toeic1", phrase: "range", emoji: "📶", meaning: "範囲", example: "We offer a wide range.", exampleJa: "私たちは幅広い品ぞろえを提供する。" },
  { level: "toeic1", phrase: "setting", emoji: "⚙️", meaning: "設定、環境", example: "Adjust the setting.", exampleJa: "設定を調整して。" },
  { level: "toeic1", phrase: "apologize", emoji: "🙇", meaning: "謝る", example: "We apologize for the delay.", exampleJa: "遅延をお詫びします。" },
  { level: "toeic1", phrase: "frequent", emoji: "🔁", meaning: "頻繁な", example: "He is a frequent visitor.", exampleJa: "彼は常連客だ。" },
  { level: "toeic1", phrase: "promotion", emoji: "⬆️", meaning: "昇進、販売促進", example: "He earned a promotion.", exampleJa: "彼は昇進を勝ち取った。" },
  { level: "toeic1", phrase: "regarding", emoji: "📄", meaning: "〜に関して", example: "Regarding your order, here is an answer.", exampleJa: "ご注文に関して、回答はこちらです。" },
  { level: "toeic1", phrase: "broadcast", emoji: "📡", meaning: "放送する", example: "They broadcast the event live.", exampleJa: "彼らはその催しを生放送する。" },
  { level: "toeic1", phrase: "responsible", emoji: "🧑‍💼", meaning: "責任がある", example: "She is responsible for sales.", exampleJa: "彼女は営業の責任者だ。" },
  { level: "toeic1", phrase: "avoid", emoji: "🚫", meaning: "避ける", example: "We must avoid delays.", exampleJa: "遅延を避けねばならない。" },
  { level: "toeic1", phrase: "effective", emoji: "💥", meaning: "効果的な、有効な", example: "The rule is effective today.", exampleJa: "その規則は本日から有効だ。" },
  { level: "toeic1", phrase: "invitation", emoji: "💌", meaning: "招待", example: "Thank you for the invitation.", exampleJa: "ご招待ありがとう。" },
  { level: "toeic1", phrase: "reduce", emoji: "📉", meaning: "減らす", example: "We need to reduce costs.", exampleJa: "費用を減らす必要がある。", accept: ["cut down", "cut back"] },
  { level: "toeic1", phrase: "vehicle", emoji: "🚗", meaning: "車両、乗り物", example: "Park the vehicle here.", exampleJa: "ここに車両を停めて。" },
  { level: "toeic1", phrase: "efficient", emoji: "⚙️", meaning: "効率的な", example: "This method is efficient.", exampleJa: "この方法は効率的だ。" },
  { level: "toeic1", phrase: "manufacturer", emoji: "🏭", meaning: "製造業者", example: "The manufacturer raised prices.", exampleJa: "その製造業者は値上げした。" },
  { level: "toeic1", phrase: "comfortable", emoji: "🛋️", meaning: "快適な", example: "The chair is comfortable.", exampleJa: "その椅子は快適だ。" },
  { level: "toeic1", phrase: "journal", emoji: "📔", meaning: "雑誌、日誌", example: "She reads a science journal.", exampleJa: "彼女は科学雑誌を読む。" },
  { level: "toeic1", phrase: "distribute", emoji: "📤", meaning: "配布する、分配する", example: "Please distribute the handouts.", exampleJa: "配布資料を配ってください。" },
  { level: "toeic1", phrase: "potential", emoji: "🌱", meaning: "潜在的な、可能性", example: "He is a potential client.", exampleJa: "彼は見込み客だ。" },
  { level: "toeic1", phrase: "reschedule", emoji: "🔄", meaning: "予定を変更する", example: "We had to reschedule the meeting.", exampleJa: "会議の予定を変更せざるを得なかった。" },
  { level: "toeic1", phrase: "renew", emoji: "🔁", meaning: "更新する", example: "Renew your membership.", exampleJa: "会員資格を更新して。" },
  { level: "toeic1", phrase: "warehouse", emoji: "🏬", meaning: "倉庫", example: "The goods are in the warehouse.", exampleJa: "商品は倉庫にある。" },
  { level: "toeic1", phrase: "refund", emoji: "💵", meaning: "返金", example: "Can I get a refund?", exampleJa: "返金してもらえますか。" },
  { level: "toeic1", phrase: "advise", emoji: "🗣️", meaning: "助言する", example: "I advise you to wait.", exampleJa: "待つことをお勧めします。" },
  { level: "toeic1", phrase: "immediately", emoji: "⚡", meaning: "すぐに", example: "Call me immediately.", exampleJa: "すぐに電話して。", accept: ["as soon as possible", "right away", "asap", "at once"] },
  { level: "toeic1", phrase: "council", emoji: "🏛️", meaning: "評議会、議会", example: "The city council met.", exampleJa: "市議会が開かれた。" },
  { level: "toeic1", phrase: "device", emoji: "📱", meaning: "装置、機器", example: "The device is new.", exampleJa: "その機器は新しい。" },
  { level: "toeic1", phrase: "intended", emoji: "🎯", meaning: "意図された、対象の", example: "This guide is intended for staff.", exampleJa: "この案内は職員向けだ。" },
  { level: "toeic1", phrase: "brochure", emoji: "📰", meaning: "パンフレット", example: "Take a brochure.", exampleJa: "パンフレットをどうぞ。" },
  { level: "toeic1", phrase: "mail", emoji: "📮", meaning: "郵便、郵送する", example: "Please mail the letter.", exampleJa: "その手紙を郵送して。" },
  { level: "toeic1", phrase: "prefer", emoji: "❤️", meaning: "好む", example: "I prefer tea.", exampleJa: "私は紅茶のほうが好きだ。" },
  { level: "toeic1", phrase: "response", emoji: "📨", meaning: "返答", example: "We await your response.", exampleJa: "ご返答をお待ちしています。" },
  { level: "toeic1", phrase: "region", emoji: "🗾", meaning: "地域", example: "The region is famous for wine.", exampleJa: "その地域はワインで有名だ。" },
  { level: "toeic1", phrase: "donation", emoji: "🎗️", meaning: "寄付", example: "We received a donation.", exampleJa: "私たちは寄付を受け取った。" },
  { level: "toeic1", phrase: "quarter", emoji: "📊", meaning: "四半期、4分の1", example: "Sales rose this quarter.", exampleJa: "今四半期は売上が伸びた。" },
  { level: "toeic1", phrase: "agreement", emoji: "🤝", meaning: "合意、契約", example: "We reached an agreement.", exampleJa: "私たちは合意に達した。" },
  { level: "toeic1", phrase: "highly", emoji: "⭐", meaning: "大いに、高く", example: "The book is highly rated.", exampleJa: "その本は高く評価されている。" },
  { level: "toeic1", phrase: "result", emoji: "📈", meaning: "結果", example: "We are happy with the result.", exampleJa: "私たちはその結果に満足だ。" },
  { level: "toeic1", phrase: "assistance", emoji: "🤲", meaning: "援助", example: "Thank you for your assistance.", exampleJa: "ご援助ありがとう。" },
  { level: "toeic1", phrase: "encourage", emoji: "💪", meaning: "励ます、促す", example: "We encourage feedback.", exampleJa: "私たちは意見を歓迎する。" },
  { level: "toeic1", phrase: "individual", emoji: "🧍", meaning: "個人、個々の", example: "Each individual gets a seat.", exampleJa: "各個人に席が与えられる。" },
  { level: "toeic1", phrase: "laboratory", emoji: "🧫", meaning: "実験室", example: "The laboratory is closed.", exampleJa: "その実験室は閉まっている。" },
  { level: "toeic1", phrase: "consider", emoji: "🤔", meaning: "検討する", example: "Please consider our offer.", exampleJa: "私たちの申し出を検討してください。", accept: ["think about", "ponder"] },
  { level: "toeic1", phrase: "headquarters", emoji: "🏙️", meaning: "本社", example: "Our headquarters is in Tokyo.", exampleJa: "わが社の本社は東京にある。" },
  { level: "toeic1", phrase: "ship", emoji: "🚢", meaning: "発送する", example: "We ship the goods today.", exampleJa: "私たちは本日商品を発送する。" },
  { level: "toeic1", phrase: "commercial", emoji: "📺", meaning: "商業の、コマーシャル", example: "It is a commercial building.", exampleJa: "それは商業ビルだ。" },
  { level: "toeic1", phrase: "document", emoji: "📃", meaning: "書類", example: "Sign the document, please.", exampleJa: "書類に署名してください。" },
  { level: "toeic1", phrase: "remind", emoji: "🔔", meaning: "思い出させる", example: "Please remind me later.", exampleJa: "あとで私に念を押して。" },
  { level: "toeic1", phrase: "require", emoji: "📌", meaning: "必要とする", example: "We require a deposit.", exampleJa: "私たちは前金を必要とする。" },
  { level: "toeic1", phrase: "representative", emoji: "🧑‍💼", meaning: "代表、担当者", example: "A sales representative called.", exampleJa: "営業担当者が電話してきた。" },
  { level: "toeic1", phrase: "packaging", emoji: "📦", meaning: "包装", example: "The packaging is eco-friendly.", exampleJa: "その包装は環境に優しい。" },
  { level: "toeic1", phrase: "description", emoji: "📝", meaning: "説明、記述", example: "Read the job description.", exampleJa: "職務内容の説明を読んで。" },
  { level: "toeic1", phrase: "property", emoji: "🏠", meaning: "不動産、特性", example: "The property is for sale.", exampleJa: "その物件は売りに出ている。" },
  { level: "toeic1", phrase: "extension", emoji: "☎️", meaning: "内線、延長", example: "Dial his extension.", exampleJa: "彼の内線にかけて。" },
  { level: "toeic1", phrase: "inquire", emoji: "❓", meaning: "問い合わせる", example: "Please inquire at the desk.", exampleJa: "受付でお問い合わせください。" },
  { level: "toeic1", phrase: "merchandise", emoji: "🛍️", meaning: "商品", example: "New merchandise arrived.", exampleJa: "新商品が入荷した。" },
  { level: "toeic1", phrase: "participate", emoji: "🙌", meaning: "参加する", example: "We participate in the fair.", exampleJa: "私たちはその見本市に参加する。" },
  { level: "toeic1", phrase: "cause", emoji: "🔎", meaning: "原因、引き起こす", example: "Find the cause of the error.", exampleJa: "その誤りの原因を見つけて。" },
  { level: "toeic1", phrase: "degree", emoji: "🎓", meaning: "学位、程度", example: "She has a college degree.", exampleJa: "彼女は大卒の学位を持つ。" },
  { level: "toeic1", phrase: "directly", emoji: "➡️", meaning: "直接", example: "Contact the seller directly.", exampleJa: "売り手に直接連絡して。" },
  { level: "toeic1", phrase: "host", emoji: "🎙️", meaning: "主催する、主人", example: "We host an annual party.", exampleJa: "私たちは毎年パーティーを主催する。" },
  { level: "toeic1", phrase: "expert", emoji: "🧠", meaning: "専門家", example: "He is a marketing expert.", exampleJa: "彼はマーケティングの専門家だ。" },
  { level: "toeic1", phrase: "impress", emoji: "😲", meaning: "感動させる", example: "The plan will impress the client.", exampleJa: "その計画は顧客を感心させるだろう。" },
  { level: "toeic1", phrase: "mainly", emoji: "🎯", meaning: "主に", example: "We mainly sell online.", exampleJa: "私たちは主にオンラインで売る。" },
  { level: "toeic1", phrase: "suggestion", emoji: "💭", meaning: "提案", example: "Thank you for the suggestion.", exampleJa: "ご提案ありがとう。" },
  { level: "toeic1", phrase: "supplier", emoji: "🏭", meaning: "供給業者", example: "Our supplier is reliable.", exampleJa: "うちの供給業者は信頼できる。" },
  { level: "toeic1", phrase: "leading", emoji: "🥇", meaning: "主要な、先頭の", example: "It is a leading company.", exampleJa: "それは大手企業だ。" },
  { level: "toeic1", phrase: "organization", emoji: "🏛️", meaning: "組織", example: "She joined a nonprofit organization.", exampleJa: "彼女は非営利組織に加わった。" },
  { level: "toeic1", phrase: "release", emoji: "🚀", meaning: "発売する、公開", example: "They will release a new model.", exampleJa: "彼らは新型を発売する。" },
  { level: "toeic1", phrase: "limited", emoji: "🔒", meaning: "限られた", example: "We have limited seats.", exampleJa: "席には限りがある。" },
  { level: "toeic1", phrase: "procedure", emoji: "📋", meaning: "手順", example: "Follow the safety procedure.", exampleJa: "安全手順に従って。" },
  { level: "toeic1", phrase: "experienced", emoji: "🎖️", meaning: "経験豊富な", example: "She is an experienced manager.", exampleJa: "彼女は経験豊富な管理職だ。" },
  { level: "toeic1", phrase: "personnel", emoji: "👥", meaning: "人員、人事（部）", example: "The personnel office is upstairs.", exampleJa: "人事課は上の階だ。" },
  { level: "toeic1", phrase: "author", emoji: "✍️", meaning: "著者", example: "The author signed books.", exampleJa: "その著者は本にサインした。" },
  { level: "toeic1", phrase: "benefit", emoji: "🩺", meaning: "利益、福利厚生", example: "Health insurance is a benefit.", exampleJa: "健康保険は福利厚生の一つだ。" },
  { level: "toeic1", phrase: "focus", emoji: "🎯", meaning: "集中する、焦点", example: "Let's focus on quality.", exampleJa: "品質に集中しよう。" },
  { level: "toeic1", phrase: "update", emoji: "🔄", meaning: "更新する、最新情報", example: "Please update the file.", exampleJa: "ファイルを更新してください。" },
  { level: "toeic1", phrase: "branch", emoji: "🏦", meaning: "支店", example: "The bank has a new branch.", exampleJa: "その銀行には新しい支店がある。" },
  { level: "toeic1", phrase: "paid", emoji: "✅", meaning: "支払い済みの、有給の", example: "The bill is paid.", exampleJa: "請求書は支払い済みだ。" },
  { level: "toeic1", phrase: "unfortunately", emoji: "😞", meaning: "残念ながら", example: "Unfortunately, the shop is closed.", exampleJa: "残念ながら、その店は閉まっている。" },
  { level: "toeic1", phrase: "original", emoji: "🆕", meaning: "元の、独創的な", example: "Keep the original copy.", exampleJa: "原本を保管して。" },
  { level: "toeic1", phrase: "rent", emoji: "🏠", meaning: "家賃、賃借する", example: "We pay rent monthly.", exampleJa: "私たちは毎月家賃を払う。" },
  { level: "toeic1", phrase: "memo", emoji: "🗒️", meaning: "メモ、回覧", example: "Write a quick memo.", exampleJa: "手早くメモを書いて。" },
  { level: "toeic1", phrase: "luggage", emoji: "🧳", meaning: "手荷物", example: "Pack your luggage.", exampleJa: "荷物を詰めて。" },
  { level: "toeic1", phrase: "editor", emoji: "🖊️", meaning: "編集者", example: "The editor reviewed the article.", exampleJa: "編集者がその記事を見直した。" },
  { level: "toeic1", phrase: "exhibition", emoji: "🖼️", meaning: "展示会", example: "The exhibition opens Friday.", exampleJa: "その展示会は金曜に始まる。" },
];

// レベル定義
const LEVELS = [
  { id: "toeic1", genre: "toeic", name: "TOEIC Lv1", desc: "頻出単語（約200語）", emoji: "💼" },
];

if (typeof module !== "undefined" && module.exports) {
  module.exports = { IDIOMS, LEVELS };
}
