/**
 * 英熟語データ
 * 各熟語は以下のフィールドを持つ:
 *   level     ... 難易度 "junior"（中学）/ "high12"（高校1・2年）/ "high3"（高校3年・大学1年）
 *   phrase    ... 英熟語（穴埋め問題の正解にもなる）
 *   image     ... 意味をイメージしたイラスト（SVG）のパス。無ければ emoji を表示
 *   emoji     ... 画像が無い場合のフォールバック表示
 *   meaning   ... 日本語の意味
 *   example   ... phrase を必ず含む英語の例文
 *   exampleJa ... 例文の日本語訳
 *
 * 例文は phrase を「そのままの形」で含めること。
 * （穴埋め問題はこの example から phrase を空欄に置き換えて生成される）
 */
const IDIOMS = [
  // ============ 中学レベル (junior) ============
  {
    level: "junior",
    phrase: "break the ice",
    image: "images/break-the-ice.svg",
    emoji: "🧊",
    meaning: "（初対面などで）緊張をほぐす、打ち解ける",
    example: "He told a joke to break the ice at the meeting.",
    exampleJa: "彼は会議で打ち解けるために冗談を言った。",
  },
  {
    level: "junior",
    phrase: "a piece of cake",
    image: "images/a-piece-of-cake.svg",
    emoji: "🍰",
    meaning: "とても簡単なこと、朝飯前",
    example: "The test was a piece of cake for her.",
    exampleJa: "そのテストは彼女にとって朝飯前だった。",
  },
  {
    level: "junior",
    phrase: "under the weather",
    image: "images/under-the-weather.svg",
    emoji: "🤒",
    meaning: "体調が悪い、気分がすぐれない",
    example: "I am feeling under the weather today.",
    exampleJa: "今日は体調がよくない。",
  },
  {
    level: "junior",
    phrase: "call it a day",
    image: "images/call-it-a-day.svg",
    emoji: "🌇",
    meaning: "その日の作業を切り上げる、終わりにする",
    example: "We worked hard, so let's call it a day.",
    exampleJa: "よく働いたから、今日はもう終わりにしよう。",
  },
  {
    level: "junior",
    phrase: "get up",
    emoji: "🌅",
    meaning: "起きる、起床する",
    example: "I get up at seven every morning.",
    exampleJa: "私は毎朝7時に起きる。",
  },
  {
    level: "junior",
    phrase: "give up",
    emoji: "🏳️",
    meaning: "あきらめる",
    example: "Never give up on your dreams.",
    exampleJa: "夢を決してあきらめないで。",
  },
  {
    level: "junior",
    phrase: "look for",
    emoji: "🔍",
    meaning: "〜を探す",
    example: "I always look for the cheapest ticket.",
    exampleJa: "私はいつも一番安い切符を探す。",
  },
  {
    level: "junior",
    phrase: "look forward to",
    emoji: "🤗",
    meaning: "〜を楽しみに待つ",
    example: "I look forward to seeing you again.",
    exampleJa: "またお会いできるのを楽しみにしています。",
  },
  {
    level: "junior",
    phrase: "take care of",
    emoji: "🩺",
    meaning: "〜の世話をする",
    example: "Please take care of my dog while I am away.",
    exampleJa: "留守の間、犬の世話をしてください。",
  },
  {
    level: "junior",
    phrase: "for example",
    emoji: "💡",
    meaning: "たとえば",
    example: "I like sports, for example soccer and tennis.",
    exampleJa: "私はスポーツ、たとえばサッカーやテニスが好きだ。",
  },
  {
    level: "junior",
    phrase: "a lot of",
    emoji: "🗂️",
    meaning: "たくさんの",
    example: "She has a lot of friends at school.",
    exampleJa: "彼女は学校にたくさんの友達がいる。",
  },
  {
    level: "junior",
    phrase: "get on",
    emoji: "🚌",
    meaning: "（乗り物に）乗る",
    example: "We get on the bus at this stop.",
    exampleJa: "私たちはこの停留所でバスに乗る。",
  },
  {
    level: "junior",
    phrase: "wake up",
    emoji: "⏰",
    meaning: "目を覚ます",
    example: "I wake up early every day.",
    exampleJa: "私は毎日早く目を覚ます。",
  },
  {
    level: "junior",
    phrase: "good at",
    emoji: "🎯",
    meaning: "〜が得意だ",
    example: "He is good at math.",
    exampleJa: "彼は数学が得意だ。",
  },

  // ============ 高校1・2年 (high12) ============
  {
    level: "high12",
    phrase: "hit the books",
    image: "images/hit-the-books.svg",
    emoji: "📚",
    meaning: "（猛）勉強する",
    example: "I need to hit the books before the exam.",
    exampleJa: "試験前にしっかり勉強しないといけない。",
  },
  {
    level: "high12",
    phrase: "once in a blue moon",
    image: "images/once-in-a-blue-moon.svg",
    emoji: "🌙",
    meaning: "ごくまれに、めったに〜ない",
    example: "We go to the cinema once in a blue moon.",
    exampleJa: "私たちはごくまれにしか映画館に行かない。",
  },
  {
    level: "high12",
    phrase: "cost an arm and a leg",
    image: "images/cost-an-arm-and-a-leg.svg",
    emoji: "💸",
    meaning: "大金がかかる、非常に高価である",
    example: "That new phone will cost an arm and a leg.",
    exampleJa: "あの新しいスマホはとても高くつくだろう。",
  },
  {
    level: "high12",
    phrase: "on the same page",
    image: "images/on-the-same-page.svg",
    emoji: "📄",
    meaning: "認識が一致している、考えが同じ",
    example: "Let's make sure we are on the same page.",
    exampleJa: "認識が一致しているか確認しよう。",
  },
  {
    level: "high12",
    phrase: "put off",
    emoji: "⏭️",
    meaning: "延期する、先延ばしにする",
    example: "Let's not put off the meeting again.",
    exampleJa: "会議をまた延期するのはやめよう。",
  },
  {
    level: "high12",
    phrase: "come up with",
    emoji: "💭",
    meaning: "（考えなどを）思いつく",
    example: "I need to come up with a new idea.",
    exampleJa: "新しいアイデアを思いつく必要がある。",
  },
  {
    level: "high12",
    phrase: "look up to",
    emoji: "🙌",
    meaning: "〜を尊敬する",
    example: "I look up to my older brother.",
    exampleJa: "私は兄を尊敬している。",
  },
  {
    level: "high12",
    phrase: "run out of",
    emoji: "🪫",
    meaning: "〜を使い果たす、切らす",
    example: "We always run out of milk.",
    exampleJa: "うちはいつも牛乳を切らしてしまう。",
  },
  {
    level: "high12",
    phrase: "make up your mind",
    emoji: "🤔",
    meaning: "決心する",
    example: "Please make up your mind quickly.",
    exampleJa: "早く決心してください。",
  },
  {
    level: "high12",
    phrase: "get along with",
    emoji: "🤝",
    meaning: "〜と仲良くやる",
    example: "I get along with my classmates.",
    exampleJa: "私はクラスメートと仲良くやっている。",
  },
  {
    level: "high12",
    phrase: "in charge of",
    emoji: "👔",
    meaning: "〜を担当して、〜の責任者で",
    example: "She is in charge of the team.",
    exampleJa: "彼女はそのチームを担当している。",
  },
  {
    level: "high12",
    phrase: "take part in",
    emoji: "🎪",
    meaning: "〜に参加する",
    example: "I take part in the school festival every year.",
    exampleJa: "私は毎年学園祭に参加する。",
  },
  {
    level: "high12",
    phrase: "as soon as possible",
    emoji: "⚡",
    meaning: "できるだけ早く",
    example: "Please call me as soon as possible.",
    exampleJa: "できるだけ早く電話してください。",
  },
  {
    level: "high12",
    phrase: "by the way",
    emoji: "💬",
    meaning: "ところで",
    example: "By the way, where is the station?",
    exampleJa: "ところで、駅はどこですか。",
  },

  // ============ 高校3年・大学1年 (high3) ============
  {
    level: "high3",
    phrase: "let the cat out of the bag",
    image: "images/let-the-cat-out-of-the-bag.svg",
    emoji: "🐱",
    meaning: "うっかり秘密を漏らす",
    example: "Don't let the cat out of the bag about the party.",
    exampleJa: "パーティーのことをうっかり漏らさないでね。",
  },
  {
    level: "high3",
    phrase: "bite the bullet",
    image: "images/bite-the-bullet.svg",
    emoji: "😬",
    meaning: "嫌なことを覚悟してやる、ぐっとこらえる",
    example: "I decided to bite the bullet and see the dentist.",
    exampleJa: "覚悟を決めて歯医者に行くことにした。",
  },
  {
    level: "high3",
    phrase: "on the other hand",
    emoji: "⚖️",
    meaning: "一方で、他方では",
    example: "On the other hand, it is too expensive.",
    exampleJa: "一方で、それは値段が高すぎる。",
  },
  {
    level: "high3",
    phrase: "in terms of",
    emoji: "📊",
    meaning: "〜の観点から、〜に関して",
    example: "In terms of cost, this plan is better.",
    exampleJa: "コストの観点では、この案の方が良い。",
  },
  {
    level: "high3",
    phrase: "take it for granted",
    emoji: "🙏",
    meaning: "それを当然のことと思う",
    example: "We often take it for granted.",
    exampleJa: "私たちはそれをよく当然のことと思ってしまう。",
  },
  {
    level: "high3",
    phrase: "make a difference",
    emoji: "✨",
    meaning: "違いを生む、効果がある",
    example: "Your small help can make a difference.",
    exampleJa: "あなたの小さな手助けが大きな違いを生む。",
  },
  {
    level: "high3",
    phrase: "keep in touch",
    emoji: "📱",
    meaning: "連絡を取り合う",
    example: "Let's keep in touch after graduation.",
    exampleJa: "卒業後も連絡を取り合おう。",
  },
  {
    level: "high3",
    phrase: "look down on",
    emoji: "👎",
    meaning: "〜を見下す",
    example: "You should never look down on others.",
    exampleJa: "決して他人を見下してはいけない。",
  },
  {
    level: "high3",
    phrase: "stand out",
    emoji: "🌟",
    meaning: "目立つ、際立つ",
    example: "You really stand out in a crowd.",
    exampleJa: "あなたは人混みの中でとても目立つ。",
  },
  {
    level: "high3",
    phrase: "cut corners",
    emoji: "✂️",
    meaning: "手を抜く、（質を落として）近道をする",
    example: "Don't cut corners on safety.",
    exampleJa: "安全面で手を抜いてはいけない。",
  },
  {
    level: "high3",
    phrase: "get over",
    emoji: "💪",
    meaning: "（困難・病気などを）乗り越える、立ち直る",
    example: "It took months to get over the loss.",
    exampleJa: "その喪失を乗り越えるのに数か月かかった。",
  },
  {
    level: "high3",
    phrase: "rule of thumb",
    emoji: "📏",
    meaning: "経験則、大まかな目安",
    example: "As a rule of thumb, save ten percent of your income.",
    exampleJa: "経験則として、収入の10%を貯金しなさい。",
  },

  // ===== 追加バッチ1（中学レベル / junior）=====
  { level: "junior", phrase: "turn on", emoji: "🔛", meaning: "（スイッチなどを）つける", example: "Please turn on the light.", exampleJa: "電気をつけてください。" },
  { level: "junior", phrase: "turn off", emoji: "🔇", meaning: "（スイッチなどを）消す", example: "Don't forget to turn off the TV.", exampleJa: "テレビを消すのを忘れないで。" },
  { level: "junior", phrase: "put on", emoji: "🧥", meaning: "身につける、着る", example: "Put on your jacket, it is cold.", exampleJa: "寒いから上着を着なさい。" },
  { level: "junior", phrase: "take off", emoji: "✈️", meaning: "脱ぐ、（飛行機が）離陸する", example: "Please take off your shoes here.", exampleJa: "ここで靴を脱いでください。" },
  { level: "junior", phrase: "sit down", emoji: "🪑", meaning: "座る", example: "Please sit down and relax.", exampleJa: "座ってくつろいでください。" },
  { level: "junior", phrase: "stand up", emoji: "🧍", meaning: "立ち上がる", example: "Everyone, please stand up.", exampleJa: "みなさん、立ってください。" },
  { level: "junior", phrase: "come in", emoji: "🚪", meaning: "入る", example: "Please come in and have a seat.", exampleJa: "どうぞ入って座ってください。" },
  { level: "junior", phrase: "go out", emoji: "🌃", meaning: "外出する", example: "Let's go out for dinner tonight.", exampleJa: "今夜は夕食に出かけよう。" },
  { level: "junior", phrase: "wait for", emoji: "⏳", meaning: "〜を待つ", example: "I will wait for you at the station.", exampleJa: "駅であなたを待ちます。" },
  { level: "junior", phrase: "listen to", emoji: "🎧", meaning: "〜を聞く", example: "I like to listen to music.", exampleJa: "私は音楽を聞くのが好きだ。" },
  { level: "junior", phrase: "look at", emoji: "👀", meaning: "〜を見る", example: "Look at that beautiful sky.", exampleJa: "あの美しい空を見て。" },
  { level: "junior", phrase: "talk to", emoji: "💬", meaning: "〜に話しかける", example: "I need to talk to you.", exampleJa: "あなたに話があります。" },
  { level: "junior", phrase: "think about", emoji: "🤔", meaning: "〜について考える", example: "I often think about my future.", exampleJa: "私はよく将来について考える。" },
  { level: "junior", phrase: "write down", emoji: "✍️", meaning: "書き留める", example: "Please write down your name.", exampleJa: "名前を書き留めてください。" },
  { level: "junior", phrase: "find out", emoji: "🔎", meaning: "（調べて）知る", example: "I want to find out the truth.", exampleJa: "私は真実を知りたい。" },
  { level: "junior", phrase: "grow up", emoji: "🌱", meaning: "成長する、大人になる", example: "I want to grow up and travel the world.", exampleJa: "大人になって世界中を旅したい。" },
  { level: "junior", phrase: "come back", emoji: "🔙", meaning: "戻る", example: "Please come back soon.", exampleJa: "早く戻ってきてね。" },
  { level: "junior", phrase: "go back", emoji: "↩️", meaning: "戻る、帰る", example: "I want to go back home.", exampleJa: "家に帰りたい。" },
  { level: "junior", phrase: "get off", emoji: "🚉", meaning: "（乗り物を）降りる", example: "We get off the train here.", exampleJa: "私たちはここで電車を降りる。" },
  { level: "junior", phrase: "pick up", emoji: "⬆️", meaning: "拾う、車で迎えに行く", example: "Can you pick up the pen?", exampleJa: "そのペンを拾ってくれる？" },
  { level: "junior", phrase: "clean up", emoji: "🧹", meaning: "片付ける、掃除する", example: "Let's clean up the room.", exampleJa: "部屋を片付けよう。" },
  { level: "junior", phrase: "help with", emoji: "🤝", meaning: "〜を手伝う", example: "Can you help with the dishes?", exampleJa: "皿洗いを手伝ってくれる？" },
  { level: "junior", phrase: "afraid of", emoji: "😱", meaning: "〜を怖がる", example: "I am afraid of the dark.", exampleJa: "私は暗いところが怖い。" },
  { level: "junior", phrase: "interested in", emoji: "🤩", meaning: "〜に興味がある", example: "I am interested in science.", exampleJa: "私は科学に興味がある。" },
  { level: "junior", phrase: "proud of", emoji: "🥹", meaning: "〜を誇りに思う", example: "I am proud of my team.", exampleJa: "私はチームを誇りに思う。" },
  { level: "junior", phrase: "full of", emoji: "🫗", meaning: "〜でいっぱい", example: "The box is full of toys.", exampleJa: "その箱はおもちゃでいっぱいだ。" },
  { level: "junior", phrase: "a few", emoji: "🔢", meaning: "少しの（数）", example: "I have a few questions.", exampleJa: "いくつか質問があります。" },
  { level: "junior", phrase: "a little", emoji: "🤏", meaning: "少し（量）", example: "I need a little help.", exampleJa: "少し手伝いが必要だ。" },
  { level: "junior", phrase: "each other", emoji: "🤝", meaning: "お互い", example: "They help each other.", exampleJa: "彼らはお互いに助け合う。" },
  { level: "junior", phrase: "of course", emoji: "✅", meaning: "もちろん", example: "Of course you can come.", exampleJa: "もちろん来ていいよ。" },
  { level: "junior", phrase: "at first", emoji: "🥇", meaning: "最初は", example: "At first, it was hard.", exampleJa: "最初は大変だった。" },
  { level: "junior", phrase: "right now", emoji: "⏰", meaning: "今すぐ、ちょうど今", example: "I am busy right now.", exampleJa: "今ちょうど忙しい。" },
  { level: "junior", phrase: "all day", emoji: "☀️", meaning: "一日中", example: "I studied all day.", exampleJa: "私は一日中勉強した。" },
  { level: "junior", phrase: "over there", emoji: "👉", meaning: "あそこに", example: "The shop is over there.", exampleJa: "店はあそこにある。" },
  { level: "junior", phrase: "so far", emoji: "📍", meaning: "今のところ", example: "So far, so good.", exampleJa: "今のところ順調だ。" },
  { level: "junior", phrase: "one day", emoji: "📅", meaning: "いつか、ある日", example: "One day I will be a doctor.", exampleJa: "いつか医者になる。" },
  { level: "junior", phrase: "for a while", emoji: "⌛", meaning: "しばらくの間", example: "Let's rest for a while.", exampleJa: "しばらく休もう。" },
  { level: "junior", phrase: "take a walk", emoji: "🚶", meaning: "散歩する", example: "Let's take a walk in the park.", exampleJa: "公園を散歩しよう。" },
  { level: "junior", phrase: "take a look", emoji: "👁️", meaning: "見てみる", example: "Please take a look at this.", exampleJa: "これを見てみてください。" },
  { level: "junior", phrase: "have fun", emoji: "🎉", meaning: "楽しむ", example: "Have fun at the party!", exampleJa: "パーティーを楽しんでね！" },
  { level: "junior", phrase: "say hello", emoji: "👋", meaning: "あいさつする", example: "Please say hello to your mom.", exampleJa: "お母さんによろしく伝えてね。" },
  { level: "junior", phrase: "make friends", emoji: "👫", meaning: "友達を作る", example: "I want to make friends at school.", exampleJa: "学校で友達を作りたい。" },
  { level: "junior", phrase: "go shopping", emoji: "🛍️", meaning: "買い物に行く", example: "Let's go shopping this weekend.", exampleJa: "今週末に買い物に行こう。" },
  { level: "junior", phrase: "take a break", emoji: "☕", meaning: "休憩する", example: "Let's take a break now.", exampleJa: "そろそろ休憩しよう。" },

  // ===== 追加バッチ1（高校1・2年 / high12）=====
  { level: "high12", phrase: "give up on", emoji: "🏳️", meaning: "〜を見限る、あきらめる", example: "Don't give up on me.", exampleJa: "私を見限らないで。" },
  { level: "high12", phrase: "carry out", emoji: "📋", meaning: "実行する", example: "We need to carry out the plan.", exampleJa: "私たちは計画を実行する必要がある。" },
  { level: "high12", phrase: "point out", emoji: "👉", meaning: "指摘する", example: "Let me point out a problem.", exampleJa: "問題を一つ指摘させてください。" },
  { level: "high12", phrase: "turn out", emoji: "🔚", meaning: "結局〜になる、判明する", example: "Things will turn out fine.", exampleJa: "物事はきっとうまくいくよ。" },
  { level: "high12", phrase: "set up", emoji: "🛠️", meaning: "設立する、設定する", example: "Let's set up a meeting.", exampleJa: "打ち合わせを設定しよう。" },
  { level: "high12", phrase: "break down", emoji: "🚗", meaning: "故障する", example: "My old car may break down.", exampleJa: "私の古い車は故障するかもしれない。" },
  { level: "high12", phrase: "break up", emoji: "💔", meaning: "別れる、解散する", example: "They decided to break up.", exampleJa: "彼らは別れることにした。" },
  { level: "high12", phrase: "bring up", emoji: "🗣️", meaning: "話題に出す、育てる", example: "Please bring up this topic later.", exampleJa: "この話題は後で出してください。" },
  { level: "high12", phrase: "call off", emoji: "❌", meaning: "中止する", example: "They had to call off the game.", exampleJa: "彼らは試合を中止せざるを得なかった。" },
  { level: "high12", phrase: "carry on", emoji: "➡️", meaning: "続ける", example: "Please carry on with your work.", exampleJa: "そのまま仕事を続けてください。" },
  { level: "high12", phrase: "catch up", emoji: "🏃", meaning: "追いつく", example: "I need to catch up with the class.", exampleJa: "私はクラスに追いつく必要がある。" },
  { level: "high12", phrase: "cut down", emoji: "🪓", meaning: "減らす", example: "I want to cut down on sugar.", exampleJa: "砂糖を減らしたい。" },
  { level: "high12", phrase: "deal with", emoji: "🤝", meaning: "対処する", example: "I can deal with this problem.", exampleJa: "私はこの問題に対処できる。" },
  { level: "high12", phrase: "depend on", emoji: "🔗", meaning: "頼る、〜次第である", example: "You can depend on me.", exampleJa: "私を頼っていいよ。" },
  { level: "high12", phrase: "fill in", emoji: "✏️", meaning: "記入する", example: "Please fill in this form.", exampleJa: "この用紙に記入してください。" },
  { level: "high12", phrase: "figure out", emoji: "💡", meaning: "理解する、解決する", example: "I can't figure out the answer.", exampleJa: "答えがどうしても分からない。" },
  { level: "high12", phrase: "focus on", emoji: "🎯", meaning: "〜に集中する", example: "Let's focus on the goal.", exampleJa: "目標に集中しよう。" },
  { level: "high12", phrase: "give back", emoji: "↩️", meaning: "返す", example: "Please give back my book.", exampleJa: "私の本を返してください。" },
  { level: "high12", phrase: "hand in", emoji: "📥", meaning: "提出する", example: "Please hand in your homework.", exampleJa: "宿題を提出してください。" },
  { level: "high12", phrase: "hang out", emoji: "🧑‍🤝‍🧑", meaning: "遊ぶ、つるむ", example: "Let's hang out this weekend.", exampleJa: "今週末に遊ぼう。" },
  { level: "high12", phrase: "hold on", emoji: "✋", meaning: "待つ、つかまる", example: "Please hold on a moment.", exampleJa: "少し待ってください。" },
  { level: "high12", phrase: "keep up", emoji: "📈", meaning: "維持する、ついていく", example: "Keep up the good work.", exampleJa: "その調子でがんばって。" },
  { level: "high12", phrase: "look into", emoji: "🔍", meaning: "調査する", example: "We will look into the matter.", exampleJa: "私たちはその件を調査します。" },
  { level: "high12", phrase: "move on", emoji: "⏭️", meaning: "前に進む、次に移る", example: "It's time to move on.", exampleJa: "そろそろ前に進む時だ。" },
  { level: "high12", phrase: "pass away", emoji: "⚰️", meaning: "亡くなる", example: "I don't want my pet to pass away.", exampleJa: "ペットに死んでほしくない。" },
  { level: "high12", phrase: "pay attention", emoji: "👂", meaning: "注意を払う", example: "Please pay attention in class.", exampleJa: "授業中は注意を払ってください。" },
  { level: "high12", phrase: "pick out", emoji: "🫳", meaning: "選ぶ", example: "Please pick out a gift.", exampleJa: "贈り物を選んでください。" },
  { level: "high12", phrase: "put up with", emoji: "😤", meaning: "我慢する", example: "I can't put up with the noise.", exampleJa: "私はその騒音に我慢できない。" },
  { level: "high12", phrase: "show up", emoji: "🚶", meaning: "現れる", example: "He didn't show up on time.", exampleJa: "彼は時間どおりに現れなかった。" },
  { level: "high12", phrase: "take after", emoji: "👨‍👦", meaning: "（親などに）似ている", example: "I take after my father.", exampleJa: "私は父に似ている。" },
  { level: "high12", phrase: "take over", emoji: "👑", meaning: "引き継ぐ", example: "She will take over the company.", exampleJa: "彼女が会社を引き継ぐ。" },
  { level: "high12", phrase: "throw away", emoji: "🗑️", meaning: "捨てる", example: "Don't throw away the bottle.", exampleJa: "その瓶を捨てないで。" },
  { level: "high12", phrase: "turn down", emoji: "🔽", meaning: "断る、（音量を）下げる", example: "He had to turn down the offer.", exampleJa: "彼はその申し出を断らざるを得なかった。" },
  { level: "high12", phrase: "work out", emoji: "💪", meaning: "運動する、うまくいく", example: "I work out every morning.", exampleJa: "私は毎朝運動する。" },
  { level: "high12", phrase: "all of a sudden", emoji: "⚡", meaning: "突然", example: "All of a sudden, it started to rain.", exampleJa: "突然、雨が降り始めた。" },
  { level: "high12", phrase: "as well as", emoji: "➕", meaning: "〜だけでなく、〜と同様に", example: "She sings as well as dances.", exampleJa: "彼女は踊るだけでなく歌う。" },
  { level: "high12", phrase: "in addition to", emoji: "➕", meaning: "〜に加えて", example: "In addition to English, I study French.", exampleJa: "英語に加えてフランス語も勉強する。" },
  { level: "high12", phrase: "instead of", emoji: "🔄", meaning: "〜の代わりに", example: "Let's walk instead of driving.", exampleJa: "運転する代わりに歩こう。" },
  { level: "high12", phrase: "according to", emoji: "📄", meaning: "〜によると", example: "According to the news, it will snow.", exampleJa: "ニュースによると雪が降るらしい。" },
  { level: "high12", phrase: "based on", emoji: "🧱", meaning: "〜に基づいて", example: "The movie is based on a true story.", exampleJa: "その映画は実話に基づいている。" },
  { level: "high12", phrase: "made of", emoji: "🪵", meaning: "〜でできている", example: "This table is made of wood.", exampleJa: "このテーブルは木でできている。" },
  { level: "high12", phrase: "similar to", emoji: "🔁", meaning: "〜に似ている", example: "My idea is similar to yours.", exampleJa: "私の考えはあなたのと似ている。" },
  { level: "high12", phrase: "take place", emoji: "📍", meaning: "開催される、起こる", example: "The festival will take place in May.", exampleJa: "祭りは5月に開催される。" },
  { level: "high12", phrase: "make sense", emoji: "🧠", meaning: "筋が通る、理解できる", example: "That doesn't make sense to me.", exampleJa: "それは私には筋が通らない。" },
  { level: "high12", phrase: "on purpose", emoji: "😼", meaning: "わざと", example: "He broke it on purpose.", exampleJa: "彼はわざとそれを壊した。" },

  // ===== 追加バッチ1（高校3年・大学1年 / high3）=====
  { level: "high3", phrase: "in spite of", emoji: "🌧️", meaning: "〜にもかかわらず", example: "In spite of the rain, we went out.", exampleJa: "雨にもかかわらず、私たちは出かけた。" },
  { level: "high3", phrase: "as a result", emoji: "📊", meaning: "結果として", example: "As a result, sales increased.", exampleJa: "結果として、売上が増えた。" },
  { level: "high3", phrase: "for the sake of", emoji: "🙏", meaning: "〜のために", example: "He did it for the sake of his family.", exampleJa: "彼は家族のためにそれをした。" },
  { level: "high3", phrase: "in order to", emoji: "🎯", meaning: "〜するために", example: "I study hard in order to pass.", exampleJa: "私は合格するために一生懸命勉強する。" },
  { level: "high3", phrase: "when it comes to", emoji: "🗣️", meaning: "〜のことになると", example: "When it comes to cooking, she is the best.", exampleJa: "料理のことになると、彼女が一番だ。" },
  { level: "high3", phrase: "up to date", emoji: "🆕", meaning: "最新の", example: "Keep your software up to date.", exampleJa: "ソフトを最新に保ちなさい。" },
  { level: "high3", phrase: "out of date", emoji: "📅", meaning: "時代遅れの、期限切れの", example: "This map is out of date.", exampleJa: "この地図は古い。" },
  { level: "high3", phrase: "for good", emoji: "🔒", meaning: "永久に", example: "He left the town for good.", exampleJa: "彼は永久にその町を去った。" },
  { level: "high3", phrase: "by no means", emoji: "🚫", meaning: "決して〜ない", example: "It is by no means easy.", exampleJa: "それは決して簡単ではない。" },
  { level: "high3", phrase: "at stake", emoji: "🎲", meaning: "危機に瀕して、賭かって", example: "Many lives are at stake.", exampleJa: "多くの命が危機に瀕している。" },
  { level: "high3", phrase: "in the long run", emoji: "⏳", meaning: "長い目で見れば", example: "It will pay off in the long run.", exampleJa: "長い目で見れば報われる。" },
  { level: "high3", phrase: "on the verge of", emoji: "🪨", meaning: "〜の寸前で", example: "She was on the verge of tears.", exampleJa: "彼女は今にも泣きそうだった。" },
  { level: "high3", phrase: "come to terms with", emoji: "🤝", meaning: "〜と折り合いをつける", example: "It is hard to come to terms with failure.", exampleJa: "失敗を受け入れるのは難しい。" },
  { level: "high3", phrase: "take into account", emoji: "🧮", meaning: "考慮に入れる", example: "We must take into account the cost.", exampleJa: "費用を考慮に入れなければならない。" },
  { level: "high3", phrase: "make up for", emoji: "🔁", meaning: "埋め合わせる", example: "I will make up for my mistake.", exampleJa: "自分の失敗を埋め合わせます。" },
  { level: "high3", phrase: "get rid of", emoji: "🗑️", meaning: "〜を取り除く", example: "I want to get rid of this old sofa.", exampleJa: "この古いソファを処分したい。" },
  { level: "high3", phrase: "keep track of", emoji: "📋", meaning: "〜を把握する", example: "It is hard to keep track of time.", exampleJa: "時間を把握するのは難しい。" },
  { level: "high3", phrase: "lose track of", emoji: "❓", meaning: "〜を見失う", example: "I lose track of time when reading.", exampleJa: "読書中は時間を忘れてしまう。" },
  { level: "high3", phrase: "capable of", emoji: "💪", meaning: "〜ができる", example: "She is capable of great things.", exampleJa: "彼女は素晴らしいことができる。" },
  { level: "high3", phrase: "aware of", emoji: "⚠️", meaning: "〜に気づいている", example: "I am aware of the risk.", exampleJa: "私はその危険に気づいている。" },
  { level: "high3", phrase: "account for", emoji: "📊", meaning: "説明する、（割合を）占める", example: "This can account for the error.", exampleJa: "これでその誤りを説明できる。" },
  { level: "high3", phrase: "bring about", emoji: "🔄", meaning: "引き起こす", example: "The reform may bring about change.", exampleJa: "その改革は変化を引き起こすかもしれない。" },
  { level: "high3", phrase: "rule out", emoji: "🚫", meaning: "除外する", example: "We cannot rule out the possibility.", exampleJa: "その可能性は除外できない。" },
  { level: "high3", phrase: "put forward", emoji: "💡", meaning: "提案する", example: "She put forward a new idea.", exampleJa: "彼女は新しい案を提案した。" },
  { level: "high3", phrase: "set aside", emoji: "🗄️", meaning: "取っておく、脇に置く", example: "I set aside money each month.", exampleJa: "私は毎月お金を取っておく。" },
  { level: "high3", phrase: "give in", emoji: "🏳️", meaning: "屈する、降参する", example: "Don't give in to pressure.", exampleJa: "プレッシャーに屈するな。" },
  { level: "high3", phrase: "go through", emoji: "📚", meaning: "経験する、目を通す", example: "We had to go through a hard time.", exampleJa: "私たちは辛い時期を経験した。" },
  { level: "high3", phrase: "stand for", emoji: "🔤", meaning: "〜を表す、支持する", example: "What does this abbreviation stand for?", exampleJa: "この略語は何を表しますか。" },
  { level: "high3", phrase: "come across", emoji: "😮", meaning: "偶然出会う、見つける", example: "You may come across new words.", exampleJa: "新しい単語に偶然出会うかもしれない。" },
  { level: "high3", phrase: "fall behind", emoji: "🐌", meaning: "遅れる", example: "Don't fall behind in your studies.", exampleJa: "勉強で遅れを取らないように。" },
  { level: "high3", phrase: "live up to", emoji: "🎯", meaning: "（期待などに）応える", example: "He tried to live up to expectations.", exampleJa: "彼は期待に応えようとした。" },
  { level: "high3", phrase: "make the most of", emoji: "🌟", meaning: "最大限に活用する", example: "Make the most of your time.", exampleJa: "時間を最大限に活用しなさい。" },
  { level: "high3", phrase: "take advantage of", emoji: "🪜", meaning: "〜を利用する", example: "Let's take advantage of this chance.", exampleJa: "この機会を活用しよう。" },
  { level: "high3", phrase: "subject to", emoji: "📜", meaning: "〜の対象である、〜次第", example: "Prices are subject to change.", exampleJa: "価格は変更されることがある。" },
  { level: "high3", phrase: "in light of", emoji: "💡", meaning: "〜を踏まえて", example: "In light of the facts, we changed the plan.", exampleJa: "事実を踏まえて計画を変えた。" },
  { level: "high3", phrase: "at the expense of", emoji: "⚖️", meaning: "〜を犠牲にして", example: "He succeeded at the expense of his health.", exampleJa: "彼は健康を犠牲にして成功した。" },
  { level: "high3", phrase: "on behalf of", emoji: "🤝", meaning: "〜を代表して", example: "I speak on behalf of the team.", exampleJa: "私はチームを代表して話します。" },
  { level: "high3", phrase: "with regard to", emoji: "📄", meaning: "〜に関して", example: "With regard to your question, here is the answer.", exampleJa: "あなたの質問に関して、答えはこちらです。" },
  { level: "high3", phrase: "prior to", emoji: "⏮️", meaning: "〜より前に", example: "Please arrive prior to the meeting.", exampleJa: "会議の前に到着してください。" },
  { level: "high3", phrase: "owing to", emoji: "🌧️", meaning: "〜のために（原因）", example: "Owing to the storm, the train stopped.", exampleJa: "嵐のために電車が止まった。" },
  { level: "high3", phrase: "in contrast to", emoji: "🔀", meaning: "〜と対照的に", example: "In contrast to summer, winter is quiet.", exampleJa: "夏とは対照的に、冬は静かだ。" },
  { level: "high3", phrase: "bound to", emoji: "🔒", meaning: "きっと〜する、〜する運命だ", example: "She is bound to succeed.", exampleJa: "彼女はきっと成功する。" },
  { level: "high3", phrase: "carry weight", emoji: "⚖️", meaning: "影響力がある", example: "Such words carry weight.", exampleJa: "そのような言葉は影響力がある。" },
  { level: "high3", phrase: "break new ground", emoji: "🌱", meaning: "新境地を開く", example: "Their research will break new ground.", exampleJa: "彼らの研究は新境地を開くだろう。" },

  // ===== 追加バッチ2（中学レベル / junior）=====
  { level: "junior", phrase: "go to bed", emoji: "🛏️", meaning: "寝る", example: "I go to bed at ten.", exampleJa: "私は10時に寝る。" },
  { level: "junior", phrase: "brush your teeth", emoji: "🪥", meaning: "歯を磨く", example: "Please brush your teeth before bed.", exampleJa: "寝る前に歯を磨いてね。" },
  { level: "junior", phrase: "take a bath", emoji: "🛁", meaning: "風呂に入る", example: "I take a bath every night.", exampleJa: "私は毎晩風呂に入る。" },
  { level: "junior", phrase: "wash your hands", emoji: "🧼", meaning: "手を洗う", example: "Please wash your hands first.", exampleJa: "まず手を洗ってください。" },
  { level: "junior", phrase: "get dressed", emoji: "👔", meaning: "服を着る", example: "I get dressed quickly.", exampleJa: "私は素早く服を着る。" },
  { level: "junior", phrase: "have breakfast", emoji: "🍳", meaning: "朝食をとる", example: "I have breakfast at seven.", exampleJa: "私は7時に朝食をとる。" },
  { level: "junior", phrase: "have lunch", emoji: "🍱", meaning: "昼食をとる", example: "Let's have lunch together.", exampleJa: "一緒に昼食をとろう。" },
  { level: "junior", phrase: "have dinner", emoji: "🍽️", meaning: "夕食をとる", example: "We have dinner at eight.", exampleJa: "私たちは8時に夕食をとる。" },
  { level: "junior", phrase: "go home", emoji: "🏠", meaning: "帰宅する", example: "Let's go home now.", exampleJa: "もう家に帰ろう。" },
  { level: "junior", phrase: "come from", emoji: "🌍", meaning: "〜出身である", example: "I come from Japan.", exampleJa: "私は日本出身です。" },
  { level: "junior", phrase: "look like", emoji: "👯", meaning: "〜に似ている、〜のようだ", example: "You look like your sister.", exampleJa: "あなたはお姉さんに似ている。" },
  { level: "junior", phrase: "would like", emoji: "🙏", meaning: "〜が欲しい", example: "I would like some water.", exampleJa: "お水をいただきたいです。" },
  { level: "junior", phrase: "how about", emoji: "💡", meaning: "〜はどうですか", example: "How about a cup of tea?", exampleJa: "お茶を一杯どうですか。" },
  { level: "junior", phrase: "what about", emoji: "❓", meaning: "〜はどうですか", example: "What about going outside?", exampleJa: "外に出るのはどう？" },
  { level: "junior", phrase: "a kind of", emoji: "🔖", meaning: "一種の", example: "It is a kind of fruit.", exampleJa: "それは果物の一種だ。" },
  { level: "junior", phrase: "lots of", emoji: "🧺", meaning: "たくさんの", example: "There are lots of stars tonight.", exampleJa: "今夜は星がたくさんある。" },
  { level: "junior", phrase: "plenty of", emoji: "🫙", meaning: "たくさんの", example: "We have plenty of time.", exampleJa: "時間はたっぷりある。" },
  { level: "junior", phrase: "all over", emoji: "🌐", meaning: "一面に、至る所に", example: "Toys were all over the floor.", exampleJa: "おもちゃが床中に散らばっていた。" },
  { level: "junior", phrase: "right away", emoji: "🏃", meaning: "すぐに", example: "I will do it right away.", exampleJa: "すぐにやります。" },
  { level: "junior", phrase: "after school", emoji: "🎒", meaning: "放課後", example: "Let's play after school.", exampleJa: "放課後に遊ぼう。" },
  { level: "junior", phrase: "on time", emoji: "⏱️", meaning: "時間どおりに", example: "Please be on time.", exampleJa: "時間どおりに来てください。" },
  { level: "junior", phrase: "in time", emoji: "⌛", meaning: "間に合って", example: "We arrived in time.", exampleJa: "私たちは間に合って到着した。" },
  { level: "junior", phrase: "these days", emoji: "📆", meaning: "最近", example: "I am busy these days.", exampleJa: "最近は忙しい。" },
  { level: "junior", phrase: "by myself", emoji: "🧍", meaning: "ひとりで", example: "I can do it by myself.", exampleJa: "ひとりでできるよ。" },
  { level: "junior", phrase: "get home", emoji: "🏡", meaning: "帰宅する", example: "I get home at six.", exampleJa: "私は6時に帰宅する。" },
  { level: "junior", phrase: "turn around", emoji: "🔄", meaning: "振り向く、向きを変える", example: "Please turn around.", exampleJa: "後ろを向いてください。" },
  { level: "junior", phrase: "run away", emoji: "🏃", meaning: "逃げる", example: "Don't run away.", exampleJa: "逃げないで。" },
  { level: "junior", phrase: "fall down", emoji: "🤕", meaning: "転ぶ、倒れる", example: "Be careful not to fall down.", exampleJa: "転ばないように気をつけて。" },
  { level: "junior", phrase: "come on", emoji: "👏", meaning: "さあ、がんばって", example: "Come on, you can do it!", exampleJa: "さあ、君ならできる！" },
  { level: "junior", phrase: "hurry up", emoji: "⏩", meaning: "急ぐ", example: "Hurry up, we are late.", exampleJa: "急いで、遅れているよ。" },
  { level: "junior", phrase: "calm down", emoji: "😌", meaning: "落ち着く", example: "Please calm down.", exampleJa: "落ち着いてください。" },
  { level: "junior", phrase: "cheer up", emoji: "😀", meaning: "元気づける、元気を出す", example: "Cheer up, things will get better.", exampleJa: "元気出して、きっと良くなるよ。" },
  { level: "junior", phrase: "dream of", emoji: "💭", meaning: "〜を夢見る", example: "I dream of becoming a singer.", exampleJa: "私は歌手になることを夢見ている。" },
  { level: "junior", phrase: "wait a minute", emoji: "⏳", meaning: "ちょっと待って", example: "Wait a minute, please.", exampleJa: "ちょっと待ってください。" },
  { level: "junior", phrase: "good for", emoji: "👍", meaning: "〜に良い", example: "Vegetables are good for you.", exampleJa: "野菜は体に良い。" },
  { level: "junior", phrase: "ready for", emoji: "✅", meaning: "〜の準備ができて", example: "I am ready for the test.", exampleJa: "私はテストの準備ができている。" },
  { level: "junior", phrase: "late for", emoji: "⏰", meaning: "〜に遅れて", example: "Don't be late for school.", exampleJa: "学校に遅刻しないで。" },
  { level: "junior", phrase: "different from", emoji: "🔀", meaning: "〜と違う", example: "My idea is different from his.", exampleJa: "私の考えは彼のと違う。" },
  { level: "junior", phrase: "famous for", emoji: "⭐", meaning: "〜で有名", example: "Kyoto is famous for temples.", exampleJa: "京都は寺で有名だ。" },
  { level: "junior", phrase: "kind to", emoji: "🤗", meaning: "〜に親切", example: "Please be kind to animals.", exampleJa: "動物に優しくしてください。" },
  { level: "junior", phrase: "thank you for", emoji: "🙏", meaning: "〜をありがとう", example: "Thank you for your help.", exampleJa: "手伝ってくれてありがとう。" },
  { level: "junior", phrase: "a glass of", emoji: "🥛", meaning: "コップ1杯の", example: "I want a glass of water.", exampleJa: "水を一杯欲しい。" },
  { level: "junior", phrase: "a cup of", emoji: "☕", meaning: "カップ1杯の", example: "She drank a cup of coffee.", exampleJa: "彼女はコーヒーを一杯飲んだ。" },
  { level: "junior", phrase: "next to", emoji: "🔜", meaning: "〜の隣に", example: "The bank is next to the post office.", exampleJa: "銀行は郵便局の隣にある。" },
  { level: "junior", phrase: "in front of", emoji: "🚏", meaning: "〜の前に", example: "Wait in front of the station.", exampleJa: "駅の前で待っていて。" },

  // ===== 追加バッチ2（高校1・2年 / high12）=====
  { level: "high12", phrase: "come true", emoji: "✨", meaning: "実現する", example: "Dreams can come true.", exampleJa: "夢は実現することがある。" },
  { level: "high12", phrase: "get ready", emoji: "🎒", meaning: "準備する", example: "Let's get ready to go.", exampleJa: "出かける準備をしよう。" },
  { level: "high12", phrase: "give a hand", emoji: "🤝", meaning: "手を貸す", example: "Can you give a hand?", exampleJa: "手を貸してくれる？" },
  { level: "high12", phrase: "make a mistake", emoji: "❌", meaning: "間違える", example: "Everyone can make a mistake.", exampleJa: "誰でも間違えることはある。" },
  { level: "high12", phrase: "make a decision", emoji: "🧭", meaning: "決定する", example: "We must make a decision today.", exampleJa: "今日決定しなければならない。" },
  { level: "high12", phrase: "take a rest", emoji: "😴", meaning: "休む", example: "You should take a rest.", exampleJa: "休んだほうがいいよ。" },
  { level: "high12", phrase: "take a chance", emoji: "🎲", meaning: "賭けてみる、思い切ってやる", example: "Let's take a chance.", exampleJa: "思い切ってやってみよう。" },
  { level: "high12", phrase: "get in touch", emoji: "📞", meaning: "連絡を取る", example: "I will get in touch soon.", exampleJa: "すぐに連絡します。" },
  { level: "high12", phrase: "keep in mind", emoji: "🧠", meaning: "心に留める", example: "Please keep in mind the rules.", exampleJa: "ルールを心に留めておいて。" },
  { level: "high12", phrase: "make progress", emoji: "📈", meaning: "進歩する", example: "We want to make progress.", exampleJa: "私たちは進歩したい。" },
  { level: "high12", phrase: "have a good time", emoji: "🥳", meaning: "楽しい時を過ごす", example: "I hope you have a good time.", exampleJa: "楽しい時間を過ごせますように。" },
  { level: "high12", phrase: "about to", emoji: "🔜", meaning: "まさに〜しようとして", example: "I am about to leave.", exampleJa: "まさに出かけるところだ。" },
  { level: "high12", phrase: "likely to", emoji: "📊", meaning: "〜しそうだ", example: "It is likely to rain.", exampleJa: "雨が降りそうだ。" },
  { level: "high12", phrase: "willing to", emoji: "🙌", meaning: "喜んで〜する", example: "I am willing to help.", exampleJa: "喜んで手伝います。" },
  { level: "high12", phrase: "supposed to", emoji: "📋", meaning: "〜することになっている", example: "You are supposed to wait here.", exampleJa: "あなたはここで待つことになっている。" },
  { level: "high12", phrase: "used to", emoji: "🕰️", meaning: "以前は〜だった", example: "I used to live in Tokyo.", exampleJa: "私は以前東京に住んでいた。" },
  { level: "high12", phrase: "so that", emoji: "🎯", meaning: "〜するように", example: "Study hard so that you pass.", exampleJa: "合格するように一生懸命勉強しなさい。" },
  { level: "high12", phrase: "as long as", emoji: "⏳", meaning: "〜する限り", example: "You can stay as long as you like.", exampleJa: "好きなだけいていいよ。" },
  { level: "high12", phrase: "no longer", emoji: "🚫", meaning: "もはや〜ない", example: "He is no longer here.", exampleJa: "彼はもうここにいない。" },
  { level: "high12", phrase: "no matter what", emoji: "💪", meaning: "何があっても", example: "No matter what, I will try.", exampleJa: "何があっても、私は挑戦する。" },
  { level: "high12", phrase: "as if", emoji: "🎭", meaning: "まるで〜のように", example: "He talks as if he knows everything.", exampleJa: "彼はまるで何でも知っているかのように話す。" },
  { level: "high12", phrase: "even though", emoji: "🤨", meaning: "〜だけれども", example: "Even though it rained, we played.", exampleJa: "雨が降ったけれど、私たちは遊んだ。" },
  { level: "high12", phrase: "in fact", emoji: "📌", meaning: "実は、実際は", example: "In fact, I already knew.", exampleJa: "実は、もう知っていた。" },
  { level: "high12", phrase: "for sure", emoji: "✅", meaning: "確実に", example: "I will come for sure.", exampleJa: "必ず行きます。" },
  { level: "high12", phrase: "at least", emoji: "🔻", meaning: "少なくとも", example: "Sleep at least seven hours.", exampleJa: "少なくとも7時間は寝なさい。" },
  { level: "high12", phrase: "at most", emoji: "🔺", meaning: "多くても", example: "It costs ten dollars at most.", exampleJa: "多くても10ドルだ。" },
  { level: "high12", phrase: "more or less", emoji: "⚖️", meaning: "だいたい、多かれ少なかれ", example: "The work is more or less done.", exampleJa: "仕事はだいたい終わっている。" },
  { level: "high12", phrase: "up and down", emoji: "↕️", meaning: "上下に、行ったり来たり", example: "She walked up and down.", exampleJa: "彼女は行ったり来たりした。" },
  { level: "high12", phrase: "day by day", emoji: "📅", meaning: "日ごとに", example: "He is improving day by day.", exampleJa: "彼は日ごとに上達している。" },
  { level: "high12", phrase: "little by little", emoji: "🐢", meaning: "少しずつ", example: "Learn little by little.", exampleJa: "少しずつ学びなさい。" },
  { level: "high12", phrase: "side by side", emoji: "👬", meaning: "並んで", example: "They sat side by side.", exampleJa: "彼らは並んで座った。" },
  { level: "high12", phrase: "first of all", emoji: "1️⃣", meaning: "まず第一に", example: "First of all, let's start.", exampleJa: "まず第一に、始めよう。" },
  { level: "high12", phrase: "after all", emoji: "🤷", meaning: "結局、なんといっても", example: "After all, it was worth it.", exampleJa: "結局、それだけの価値があった。" },
  { level: "high12", phrase: "care about", emoji: "❤️", meaning: "〜を気にかける", example: "I care about my friends.", exampleJa: "私は友達を大切に思っている。" },
  { level: "high12", phrase: "believe in", emoji: "🙏", meaning: "〜を信じる", example: "I believe in you.", exampleJa: "私はあなたを信じている。" },
  { level: "high12", phrase: "apply for", emoji: "📝", meaning: "〜に応募する", example: "I want to apply for the job.", exampleJa: "その仕事に応募したい。" },
  { level: "high12", phrase: "agree with", emoji: "🤝", meaning: "〜に同意する", example: "I agree with you.", exampleJa: "私はあなたに同意する。" },
  { level: "high12", phrase: "belong to", emoji: "🏷️", meaning: "〜に属する、〜のものだ", example: "These belong to me.", exampleJa: "これらは私のものだ。" },
  { level: "high12", phrase: "consist of", emoji: "🧩", meaning: "〜から成る", example: "Teams consist of five players.", exampleJa: "チームは5人の選手から成る。" },
  { level: "high12", phrase: "prepare for", emoji: "🎒", meaning: "〜に備える", example: "We prepare for the exam.", exampleJa: "私たちは試験に備える。" },
  { level: "high12", phrase: "search for", emoji: "🔦", meaning: "〜を探す", example: "They search for the answer.", exampleJa: "彼らは答えを探す。" },
  { level: "high12", phrase: "wait in line", emoji: "🚶", meaning: "列に並んで待つ", example: "Please wait in line.", exampleJa: "列に並んでお待ちください。" },
  { level: "high12", phrase: "take turns", emoji: "🔄", meaning: "交代でする", example: "Let's take turns.", exampleJa: "交代でやろう。" },

  // ===== 追加バッチ2（高校3年・大学1年 / high3）=====
  { level: "high3", phrase: "in advance", emoji: "🕐", meaning: "前もって", example: "Please book in advance.", exampleJa: "前もって予約してください。" },
  { level: "high3", phrase: "on the whole", emoji: "🌐", meaning: "概して", example: "On the whole, it went well.", exampleJa: "概して、うまくいった。" },
  { level: "high3", phrase: "for the most part", emoji: "📊", meaning: "大部分は", example: "For the most part, I agree.", exampleJa: "大部分は同意します。" },
  { level: "high3", phrase: "to some extent", emoji: "📏", meaning: "ある程度", example: "I agree to some extent.", exampleJa: "ある程度は同意する。" },
  { level: "high3", phrase: "as a matter of fact", emoji: "📌", meaning: "実のところ", example: "As a matter of fact, I disagree.", exampleJa: "実のところ、私は反対だ。" },
  { level: "high3", phrase: "in other words", emoji: "🔤", meaning: "言い換えれば", example: "In other words, we failed.", exampleJa: "言い換えれば、私たちは失敗した。" },
  { level: "high3", phrase: "in particular", emoji: "🎯", meaning: "特に", example: "I like fruit, in particular apples.", exampleJa: "私は果物、特にりんごが好きだ。" },
  { level: "high3", phrase: "in general", emoji: "🌍", meaning: "一般的に", example: "In general, dogs are friendly.", exampleJa: "一般的に、犬は人なつこい。" },
  { level: "high3", phrase: "by means of", emoji: "🛠️", meaning: "〜によって", example: "We communicate by means of language.", exampleJa: "私たちは言語によって意思を伝える。" },
  { level: "high3", phrase: "at any rate", emoji: "🤷", meaning: "いずれにせよ", example: "At any rate, we must go.", exampleJa: "いずれにせよ、行かなければならない。" },
  { level: "high3", phrase: "for instance", emoji: "💡", meaning: "たとえば", example: "Some animals, for instance bats, fly at night.", exampleJa: "一部の動物、たとえばコウモリは夜に飛ぶ。" },
  { level: "high3", phrase: "so to speak", emoji: "🗣️", meaning: "いわば", example: "He is, so to speak, a walking dictionary.", exampleJa: "彼はいわば歩く辞書だ。" },
  { level: "high3", phrase: "needless to say", emoji: "🙊", meaning: "言うまでもなく", example: "Needless to say, health is important.", exampleJa: "言うまでもなく、健康は大切だ。" },
  { level: "high3", phrase: "as far as", emoji: "🛣️", meaning: "〜する限り", example: "As far as I know, it is true.", exampleJa: "私の知る限り、それは本当だ。" },
  { level: "high3", phrase: "now that", emoji: "🕐", meaning: "今や〜なので", example: "Now that you are here, let's start.", exampleJa: "君が来たから、始めよう。" },
  { level: "high3", phrase: "in case", emoji: "🧯", meaning: "〜の場合に備えて", example: "Take an umbrella in case it rains.", exampleJa: "雨に備えて傘を持って行きなさい。" },
  { level: "high3", phrase: "given that", emoji: "📐", meaning: "〜を考えると", example: "Given that it is late, let's stop.", exampleJa: "遅いことを考えると、やめておこう。" },
  { level: "high3", phrase: "let alone", emoji: "🚫", meaning: "〜はおろか", example: "He can't walk, let alone run.", exampleJa: "彼は走るどころか歩けない。" },
  { level: "high3", phrase: "as opposed to", emoji: "🔀", meaning: "〜とは対照的に", example: "I prefer tea, as opposed to coffee.", exampleJa: "私はコーヒーではなく紅茶が好きだ。" },
  { level: "high3", phrase: "in return", emoji: "🔄", meaning: "お返しに", example: "She helped me, and I helped her in return.", exampleJa: "彼女は私を助け、私もお返しに助けた。" },
  { level: "high3", phrase: "at the same time", emoji: "⏱️", meaning: "同時に", example: "He laughed and cried at the same time.", exampleJa: "彼は同時に笑い泣きした。" },
  { level: "high3", phrase: "on the contrary", emoji: "🙅", meaning: "それどころか", example: "On the contrary, it is easy.", exampleJa: "それどころか、簡単だ。" },
  { level: "high3", phrase: "by chance", emoji: "🍀", meaning: "偶然に", example: "I met her by chance.", exampleJa: "私は偶然彼女に会った。" },
  { level: "high3", phrase: "out of order", emoji: "🚧", meaning: "故障して", example: "The elevator is out of order.", exampleJa: "エレベーターは故障している。" },
  { level: "high3", phrase: "out of the question", emoji: "🚫", meaning: "問題外で", example: "Quitting is out of the question.", exampleJa: "やめるなんて問題外だ。" },
  { level: "high3", phrase: "in vain", emoji: "💨", meaning: "無駄に", example: "All his efforts were in vain.", exampleJa: "彼の努力はすべて無駄だった。" },
  { level: "high3", phrase: "at ease", emoji: "😌", meaning: "くつろいで", example: "Please feel at ease.", exampleJa: "どうぞくつろいでください。" },
  { level: "high3", phrase: "ahead of", emoji: "🥇", meaning: "〜より先に、〜に先んじて", example: "He finished ahead of others.", exampleJa: "彼は他の人より先に終えた。" },
  { level: "high3", phrase: "apart from", emoji: "➗", meaning: "〜は別として", example: "Apart from that, all is fine.", exampleJa: "それは別として、すべて順調だ。" },
  { level: "high3", phrase: "regardless of", emoji: "🚫", meaning: "〜に関係なく", example: "Everyone is welcome, regardless of age.", exampleJa: "年齢に関係なく誰でも歓迎だ。" },
  { level: "high3", phrase: "by virtue of", emoji: "🏅", meaning: "〜のおかげで", example: "He won by virtue of hard work.", exampleJa: "彼は努力のおかげで勝った。" },
  { level: "high3", phrase: "in accordance with", emoji: "📜", meaning: "〜に従って", example: "Act in accordance with the rules.", exampleJa: "規則に従って行動しなさい。" },
  { level: "high3", phrase: "with respect to", emoji: "📄", meaning: "〜に関して", example: "With respect to safety, we are careful.", exampleJa: "安全に関しては、私たちは慎重だ。" },
  { level: "high3", phrase: "in response to", emoji: "📨", meaning: "〜に応えて", example: "In response to the demand, they acted.", exampleJa: "要望に応えて、彼らは動いた。" },
  { level: "high3", phrase: "in the wake of", emoji: "🌊", meaning: "〜の余波で、〜の後を受けて", example: "Prices rose in the wake of the crisis.", exampleJa: "危機の余波で物価が上がった。" },
  { level: "high3", phrase: "at the mercy of", emoji: "🌀", meaning: "〜のなすがままに", example: "Sailors are at the mercy of the sea.", exampleJa: "船乗りは海のなすがままだ。" },
  { level: "high3", phrase: "in the face of", emoji: "🛡️", meaning: "〜に直面して", example: "She stayed calm in the face of danger.", exampleJa: "彼女は危険に直面しても冷静だった。" },
  { level: "high3", phrase: "on the grounds that", emoji: "⚖️", meaning: "〜という理由で", example: "He refused on the grounds that it was unfair.", exampleJa: "彼は不公平だという理由で断った。" },
  { level: "high3", phrase: "to the point", emoji: "🎯", meaning: "要点を突いて", example: "Her speech was short and to the point.", exampleJa: "彼女の話は短く要点を突いていた。" },
  { level: "high3", phrase: "beside the point", emoji: "🚪", meaning: "的外れで", example: "That argument is beside the point.", exampleJa: "その議論は的外れだ。" },
  { level: "high3", phrase: "at odds with", emoji: "⚔️", meaning: "〜と対立して", example: "He is at odds with his boss.", exampleJa: "彼は上司と対立している。" },
  { level: "high3", phrase: "in proportion to", emoji: "📈", meaning: "〜に比例して", example: "Pay rises in proportion to effort.", exampleJa: "給料は努力に比例して上がる。" },
  { level: "high3", phrase: "for the time being", emoji: "⏳", meaning: "当面は", example: "Stay here for the time being.", exampleJa: "当面はここにいなさい。" },
  { level: "high3", phrase: "on second thought", emoji: "🤔", meaning: "考え直して", example: "On second thought, let's wait.", exampleJa: "考え直して、待つことにしよう。" },
  { level: "high3", phrase: "all the same", emoji: "🟰", meaning: "それでもやはり", example: "It is risky, but I will do it all the same.", exampleJa: "危険だが、それでもやる。" },

  // ===== 追加バッチ3（中学レベル / junior）=====
  { level: "junior", phrase: "every day", emoji: "📆", meaning: "毎日", example: "I practice every day.", exampleJa: "私は毎日練習する。" },
  { level: "junior", phrase: "last night", emoji: "🌙", meaning: "昨夜", example: "I slept well last night.", exampleJa: "昨夜はよく眠れた。" },
  { level: "junior", phrase: "this morning", emoji: "🌅", meaning: "今朝", example: "I was busy this morning.", exampleJa: "今朝は忙しかった。" },
  { level: "junior", phrase: "at home", emoji: "🏠", meaning: "家で", example: "I stayed at home.", exampleJa: "私は家にいた。" },
  { level: "junior", phrase: "at school", emoji: "🏫", meaning: "学校で", example: "I study at school.", exampleJa: "私は学校で勉強する。" },
  { level: "junior", phrase: "at night", emoji: "🌃", meaning: "夜に", example: "Stars shine at night.", exampleJa: "星は夜に輝く。" },
  { level: "junior", phrase: "go for a walk", emoji: "🚶", meaning: "散歩に行く", example: "Let's go for a walk.", exampleJa: "散歩に行こう。" },
  { level: "junior", phrase: "play with", emoji: "🧸", meaning: "〜と遊ぶ", example: "I play with my dog.", exampleJa: "私は犬と遊ぶ。" },
  { level: "junior", phrase: "wait and see", emoji: "👀", meaning: "様子を見る", example: "Let's wait and see.", exampleJa: "様子を見よう。" },
  { level: "junior", phrase: "come over", emoji: "🚪", meaning: "立ち寄る、家に来る", example: "Please come over tonight.", exampleJa: "今夜うちに来てね。" },
  { level: "junior", phrase: "eat out", emoji: "🍴", meaning: "外食する", example: "Let's eat out tonight.", exampleJa: "今夜は外食しよう。" },
  { level: "junior", phrase: "stay up", emoji: "🌙", meaning: "夜更かしする", example: "Don't stay up too late.", exampleJa: "夜更かししすぎないで。" },
  { level: "junior", phrase: "go on", emoji: "▶️", meaning: "続ける、進む", example: "Please go on with the story.", exampleJa: "話を続けてください。" },
  { level: "junior", phrase: "get well", emoji: "🤧", meaning: "（病気が）治る", example: "I hope you get well soon.", exampleJa: "早く良くなりますように。" },
  { level: "junior", phrase: "feel better", emoji: "🙂", meaning: "気分が良くなる", example: "I feel better now.", exampleJa: "もう気分が良くなった。" },
  { level: "junior", phrase: "take a picture", emoji: "📷", meaning: "写真を撮る", example: "Let's take a picture here.", exampleJa: "ここで写真を撮ろう。" },
  { level: "junior", phrase: "ride a bike", emoji: "🚲", meaning: "自転車に乗る", example: "I ride a bike to school.", exampleJa: "私は自転車で学校に行く。" },
  { level: "junior", phrase: "catch a cold", emoji: "🤧", meaning: "風邪をひく", example: "Don't catch a cold.", exampleJa: "風邪をひかないで。" },
  { level: "junior", phrase: "make a noise", emoji: "🔊", meaning: "音を立てる、騒ぐ", example: "Please don't make a noise.", exampleJa: "音を立てないでください。" },
  { level: "junior", phrase: "tell a lie", emoji: "🤥", meaning: "うそをつく", example: "Don't tell a lie.", exampleJa: "うそをつかないで。" },
  { level: "junior", phrase: "tell the truth", emoji: "💯", meaning: "本当のことを言う", example: "Please tell the truth.", exampleJa: "本当のことを言ってください。" },
  { level: "junior", phrase: "keep a diary", emoji: "📔", meaning: "日記をつける", example: "I keep a diary.", exampleJa: "私は日記をつけている。" },
  { level: "junior", phrase: "do my best", emoji: "💪", meaning: "全力を尽くす", example: "I will do my best.", exampleJa: "全力を尽くします。" },
  { level: "junior", phrase: "on foot", emoji: "🚶", meaning: "徒歩で", example: "I go to school on foot.", exampleJa: "私は徒歩で学校に行く。" },
  { level: "junior", phrase: "by bus", emoji: "🚌", meaning: "バスで", example: "I go by bus.", exampleJa: "私はバスで行く。" },
  { level: "junior", phrase: "by train", emoji: "🚆", meaning: "電車で", example: "She goes by train.", exampleJa: "彼女は電車で行く。" },
  { level: "junior", phrase: "by car", emoji: "🚗", meaning: "車で", example: "We travel by car.", exampleJa: "私たちは車で移動する。" },
  { level: "junior", phrase: "a pair of", emoji: "👟", meaning: "一組の", example: "I bought a pair of shoes.", exampleJa: "私は靴を一足買った。" },
  { level: "junior", phrase: "some of", emoji: "🧮", meaning: "〜のいくつか", example: "Some of them are new.", exampleJa: "それらのいくつかは新しい。" },
  { level: "junior", phrase: "most of", emoji: "📊", meaning: "〜の大部分", example: "Most of the students agreed.", exampleJa: "生徒の大部分が賛成した。" },
  { level: "junior", phrase: "both of", emoji: "👥", meaning: "〜の両方", example: "Both of them came.", exampleJa: "二人とも来た。" },
  { level: "junior", phrase: "one of", emoji: "1️⃣", meaning: "〜のひとつ", example: "He is one of my friends.", exampleJa: "彼は私の友達の一人だ。" },
  { level: "junior", phrase: "far from", emoji: "🚫", meaning: "〜から遠い、〜どころか", example: "The school is far from here.", exampleJa: "学校はここから遠い。" },
  { level: "junior", phrase: "close to", emoji: "📍", meaning: "〜に近い", example: "My house is close to the park.", exampleJa: "私の家は公園に近い。" },
  { level: "junior", phrase: "next time", emoji: "⏭️", meaning: "次回", example: "See you next time.", exampleJa: "また次回ね。" },
  { level: "junior", phrase: "last time", emoji: "⏮️", meaning: "前回", example: "Last time was fun.", exampleJa: "前回は楽しかった。" },
  { level: "junior", phrase: "so much", emoji: "💕", meaning: "とても、たくさん", example: "Thank you so much.", exampleJa: "本当にありがとう。" },
  { level: "junior", phrase: "too much", emoji: "🛑", meaning: "〜すぎる", example: "Don't eat too much.", exampleJa: "食べすぎないで。" },
  { level: "junior", phrase: "not at all", emoji: "🙅", meaning: "全く〜ない", example: "He was not at all afraid.", exampleJa: "彼は全く怖がっていなかった。" },
  { level: "junior", phrase: "as usual", emoji: "🔁", meaning: "いつものように", example: "He was late, as usual.", exampleJa: "彼はいつものように遅刻した。" },
  { level: "junior", phrase: "just a moment", emoji: "⏳", meaning: "少々お待ちを", example: "Just a moment, please.", exampleJa: "少々お待ちください。" },
  { level: "junior", phrase: "no problem", emoji: "👌", meaning: "問題ない", example: "No problem, I can help.", exampleJa: "問題ないよ、手伝える。" },
  { level: "junior", phrase: "excuse me", emoji: "🙇", meaning: "すみません", example: "Excuse me, where is the station?", exampleJa: "すみません、駅はどこですか。" },
  { level: "junior", phrase: "good luck", emoji: "🍀", meaning: "幸運を", example: "Good luck on your test!", exampleJa: "テスト頑張ってね！" },

  // ===== 追加バッチ3（高校1・2年 / high12）=====
  { level: "high12", phrase: "end up", emoji: "🔚", meaning: "結局〜になる", example: "You may end up tired.", exampleJa: "結局疲れてしまうかもしれない。" },
  { level: "high12", phrase: "go ahead", emoji: "✅", meaning: "先に進む、どうぞ", example: "Go ahead and start.", exampleJa: "どうぞ始めてください。" },
  { level: "high12", phrase: "go over", emoji: "🔁", meaning: "見直す、確認する", example: "Let's go over the plan.", exampleJa: "計画を見直そう。" },
  { level: "high12", phrase: "look around", emoji: "👀", meaning: "見回す", example: "Let's look around the shop.", exampleJa: "店の中を見て回ろう。" },
  { level: "high12", phrase: "set off", emoji: "🧨", meaning: "出発する、引き起こす", example: "We set off early.", exampleJa: "私たちは早く出発した。" },
  { level: "high12", phrase: "take down", emoji: "📝", meaning: "書き留める、取り外す", example: "Please take down this number.", exampleJa: "この番号を書き留めてください。" },
  { level: "high12", phrase: "put away", emoji: "🗄️", meaning: "片付ける", example: "Put away your toys.", exampleJa: "おもちゃを片付けなさい。" },
  { level: "high12", phrase: "put together", emoji: "🧩", meaning: "組み立てる、まとめる", example: "Let's put together a plan.", exampleJa: "計画をまとめよう。" },
  { level: "high12", phrase: "work on", emoji: "🛠️", meaning: "〜に取り組む", example: "I work on my project daily.", exampleJa: "私は毎日課題に取り組む。" },
  { level: "high12", phrase: "come along", emoji: "🚶", meaning: "一緒に来る、進展する", example: "Come along with us.", exampleJa: "一緒に来てよ。" },
  { level: "high12", phrase: "drop by", emoji: "🚪", meaning: "立ち寄る", example: "Please drop by anytime.", exampleJa: "いつでも立ち寄ってね。" },
  { level: "high12", phrase: "drop out", emoji: "🎓", meaning: "中退する、脱落する", example: "He may drop out of school.", exampleJa: "彼は学校を中退するかもしれない。" },
  { level: "high12", phrase: "fill out", emoji: "🖊️", meaning: "（書類に）記入する", example: "Please fill out the form.", exampleJa: "用紙に記入してください。" },
  { level: "high12", phrase: "give out", emoji: "📤", meaning: "配る、尽きる", example: "They give out free samples.", exampleJa: "彼らは無料サンプルを配る。" },
  { level: "high12", phrase: "hand out", emoji: "🗂️", meaning: "配る", example: "Please hand out the papers.", exampleJa: "プリントを配ってください。" },
  { level: "high12", phrase: "keep on", emoji: "🔁", meaning: "〜し続ける", example: "Keep on trying.", exampleJa: "挑戦し続けて。" },
  { level: "high12", phrase: "let down", emoji: "😞", meaning: "失望させる", example: "Don't let down your friends.", exampleJa: "友達を失望させないで。" },
  { level: "high12", phrase: "make out", emoji: "👁️", meaning: "理解する、見分ける", example: "I can't make out his writing.", exampleJa: "彼の字が読み取れない。" },
  { level: "high12", phrase: "pass by", emoji: "🚶", meaning: "通り過ぎる", example: "We pass by the park.", exampleJa: "私たちは公園のそばを通る。" },
  { level: "high12", phrase: "put down", emoji: "🔽", meaning: "下に置く、書き留める", example: "Please put down the box.", exampleJa: "その箱を下に置いてください。" },
  { level: "high12", phrase: "run into", emoji: "😮", meaning: "偶然出会う、ぶつかる", example: "I run into him sometimes.", exampleJa: "私は時々彼に偶然会う。" },
  { level: "high12", phrase: "take up", emoji: "🎯", meaning: "（趣味などを）始める、占める", example: "I want to take up tennis.", exampleJa: "テニスを始めたい。" },
  { level: "high12", phrase: "think over", emoji: "🤔", meaning: "よく考える", example: "Please think over my offer.", exampleJa: "私の申し出をよく考えてください。" },
  { level: "high12", phrase: "try on", emoji: "👗", meaning: "試着する", example: "May I try on this shirt?", exampleJa: "このシャツを試着してもいい？" },
  { level: "high12", phrase: "turn up", emoji: "🔼", meaning: "現れる、（音量を）上げる", example: "He may turn up late.", exampleJa: "彼は遅れて現れるかもしれない。" },
  { level: "high12", phrase: "watch out", emoji: "⚠️", meaning: "気をつける", example: "Watch out for cars.", exampleJa: "車に気をつけて。" },
  { level: "high12", phrase: "wear out", emoji: "😩", meaning: "すり減らす、疲れさせる", example: "These shoes will wear out.", exampleJa: "この靴はすり減るだろう。" },
  { level: "high12", phrase: "get back", emoji: "🔙", meaning: "戻る、取り戻す", example: "I will get back soon.", exampleJa: "すぐ戻ります。" },
  { level: "high12", phrase: "go down", emoji: "📉", meaning: "下がる", example: "Prices may go down.", exampleJa: "価格は下がるかもしれない。" },
  { level: "high12", phrase: "go up", emoji: "📈", meaning: "上がる", example: "Prices may go up.", exampleJa: "価格は上がるかもしれない。" },
  { level: "high12", phrase: "break in", emoji: "🔓", meaning: "押し入る、慣らす", example: "A thief tried to break in.", exampleJa: "泥棒が押し入ろうとした。" },
  { level: "high12", phrase: "check in", emoji: "🛎️", meaning: "チェックインする", example: "Let's check in at the hotel.", exampleJa: "ホテルでチェックインしよう。" },
  { level: "high12", phrase: "check out", emoji: "🚪", meaning: "チェックアウトする、調べる", example: "Let's check out this shop.", exampleJa: "この店を見てみよう。" },
  { level: "high12", phrase: "count on", emoji: "🤞", meaning: "頼りにする", example: "You can count on me.", exampleJa: "私を頼っていいよ。" },
  { level: "high12", phrase: "major in", emoji: "🎓", meaning: "専攻する", example: "I want to major in history.", exampleJa: "歴史を専攻したい。" },
  { level: "high12", phrase: "result in", emoji: "🔚", meaning: "結果として〜になる", example: "It may result in success.", exampleJa: "それは成功につながるかもしれない。" },
  { level: "high12", phrase: "result from", emoji: "🔙", meaning: "〜から生じる", example: "Errors result from haste.", exampleJa: "間違いは焦りから生じる。" },
  { level: "high12", phrase: "succeed in", emoji: "🏆", meaning: "〜に成功する", example: "I hope to succeed in business.", exampleJa: "ビジネスで成功したい。" },
  { level: "high12", phrase: "specialize in", emoji: "🔬", meaning: "〜を専門にする", example: "We specialize in design.", exampleJa: "私たちはデザインを専門にしている。" },
  { level: "high12", phrase: "go through with", emoji: "✔️", meaning: "やり通す", example: "She will go through with the plan.", exampleJa: "彼女は計画をやり通すだろう。" },

  // ===== 追加バッチ3（高校3年・大学1年 / high3）=====
  { level: "high3", phrase: "once and for all", emoji: "🔚", meaning: "きっぱりと、これを最後に", example: "Let's settle this once and for all.", exampleJa: "これを最後にきっぱり片を付けよう。" },
  { level: "high3", phrase: "by and large", emoji: "🌐", meaning: "概して", example: "By and large, it works.", exampleJa: "概して、それは機能する。" },
  { level: "high3", phrase: "all in all", emoji: "🧮", meaning: "全体として", example: "All in all, it was a good day.", exampleJa: "全体として、良い一日だった。" },
  { level: "high3", phrase: "in the end", emoji: "🔚", meaning: "最終的に", example: "In the end, we won.", exampleJa: "最終的に、私たちは勝った。" },
  { level: "high3", phrase: "at the end of", emoji: "📅", meaning: "〜の終わりに", example: "At the end of the day, take a rest.", exampleJa: "一日の終わりには休みなさい。" },
  { level: "high3", phrase: "on the basis of", emoji: "🧱", meaning: "〜に基づいて", example: "We decided on the basis of facts.", exampleJa: "私たちは事実に基づいて決めた。" },
  { level: "high3", phrase: "in view of", emoji: "👀", meaning: "〜を考慮して", example: "In view of the cost, we waited.", exampleJa: "費用を考慮して、私たちは待った。" },
  { level: "high3", phrase: "with a view to", emoji: "🎯", meaning: "〜する目的で", example: "He studies with a view to passing.", exampleJa: "彼は合格する目的で勉強している。" },
  { level: "high3", phrase: "in favor of", emoji: "👍", meaning: "〜に賛成して", example: "I am in favor of the plan.", exampleJa: "私はその計画に賛成だ。" },
  { level: "high3", phrase: "at the cost of", emoji: "⚖️", meaning: "〜を犠牲にして", example: "He won at the cost of his health.", exampleJa: "彼は健康を犠牲にして勝った。" },
  { level: "high3", phrase: "for fear of", emoji: "😨", meaning: "〜を恐れて", example: "He whispered for fear of waking the baby.", exampleJa: "赤ちゃんを起こすのを恐れて彼はささやいた。" },
  { level: "high3", phrase: "by way of", emoji: "🛣️", meaning: "〜経由で、〜として", example: "We went by way of the coast.", exampleJa: "私たちは海岸沿いを経由して行った。" },
  { level: "high3", phrase: "in pursuit of", emoji: "🏃", meaning: "〜を求めて", example: "She traveled in pursuit of art.", exampleJa: "彼女は芸術を求めて旅した。" },
  { level: "high3", phrase: "on account of", emoji: "🌧️", meaning: "〜のために（原因）", example: "The game was canceled on account of rain.", exampleJa: "試合は雨のため中止された。" },
  { level: "high3", phrase: "in conjunction with", emoji: "🔗", meaning: "〜と連携して、〜と併せて", example: "Use it in conjunction with the app.", exampleJa: "アプリと併せて使ってください。" },
  { level: "high3", phrase: "as a whole", emoji: "🌍", meaning: "全体として", example: "The team, as a whole, improved.", exampleJa: "チームは全体として向上した。" },
  { level: "high3", phrase: "for one thing", emoji: "1️⃣", meaning: "ひとつには", example: "For one thing, it is cheap.", exampleJa: "ひとつには、それは安い。" },
  { level: "high3", phrase: "to begin with", emoji: "🥇", meaning: "まず初めに", example: "To begin with, let's plan.", exampleJa: "まず初めに、計画を立てよう。" },
  { level: "high3", phrase: "to make matters worse", emoji: "😱", meaning: "さらに悪いことに", example: "To make matters worse, it rained.", exampleJa: "さらに悪いことに、雨が降った。" },
  { level: "high3", phrase: "come into play", emoji: "🎬", meaning: "作用し始める", example: "Many factors come into play.", exampleJa: "多くの要因が作用する。" },
  { level: "high3", phrase: "take its toll", emoji: "💀", meaning: "悪影響を及ぼす", example: "Stress can take its toll.", exampleJa: "ストレスは悪影響を及ぼしうる。" },
  { level: "high3", phrase: "pave the way", emoji: "🛤️", meaning: "道を開く", example: "This will pave the way for change.", exampleJa: "これが変化への道を開くだろう。" },
  { level: "high3", phrase: "shed light on", emoji: "💡", meaning: "解明する、明らかにする", example: "New facts shed light on the case.", exampleJa: "新事実がその事件を明らかにする。" },
  { level: "high3", phrase: "play a role", emoji: "🎭", meaning: "役割を果たす", example: "Luck can play a role.", exampleJa: "運も役割を果たすことがある。" },
  { level: "high3", phrase: "keep an eye on", emoji: "👁️", meaning: "〜を見張る", example: "Please keep an eye on the baby.", exampleJa: "赤ちゃんを見ていてください。" },
  { level: "high3", phrase: "get the hang of", emoji: "🎯", meaning: "〜のコツをつかむ", example: "You will get the hang of it.", exampleJa: "そのうちコツをつかむよ。" },
  { level: "high3", phrase: "make ends meet", emoji: "💴", meaning: "やりくりする", example: "It is hard to make ends meet.", exampleJa: "やりくりするのは大変だ。" },
  { level: "high3", phrase: "break the news", emoji: "📰", meaning: "（重要な）知らせを伝える", example: "I had to break the news to her.", exampleJa: "私は彼女にその知らせを伝えねばならなかった。" },
  { level: "high3", phrase: "turn a blind eye", emoji: "🙈", meaning: "見て見ぬふりをする", example: "Don't turn a blind eye to it.", exampleJa: "それを見て見ぬふりしないで。" },
  { level: "high3", phrase: "hit the nail on the head", emoji: "🔨", meaning: "的を射る、まさに言い当てる", example: "You hit the nail on the head.", exampleJa: "君はまさに言い当てた。" },
  { level: "high3", phrase: "beat around the bush", emoji: "🌳", meaning: "遠回しに言う", example: "Don't beat around the bush.", exampleJa: "遠回しに言わないで。" },
  { level: "high3", phrase: "the last straw", emoji: "🐫", meaning: "我慢の限界（となるもの）", example: "That was the last straw.", exampleJa: "それが我慢の限界だった。" },
  { level: "high3", phrase: "peace of mind", emoji: "😌", meaning: "心の平安、安心", example: "This gives me peace of mind.", exampleJa: "これで安心できる。" },
  { level: "high3", phrase: "on cloud nine", emoji: "☁️", meaning: "最高に幸せで", example: "She was on cloud nine.", exampleJa: "彼女は天にも昇る気持ちだった。" },
  { level: "high3", phrase: "under control", emoji: "🎛️", meaning: "制御できて", example: "Everything is under control.", exampleJa: "すべて制御できている。" },
  { level: "high3", phrase: "out of hand", emoji: "🌀", meaning: "手に負えない", example: "Things got out of hand.", exampleJa: "事態は手に負えなくなった。" },
  { level: "high3", phrase: "in the dark", emoji: "🌑", meaning: "知らされずに", example: "I was kept in the dark.", exampleJa: "私は知らされていなかった。" },
  { level: "high3", phrase: "second to none", emoji: "🥇", meaning: "何にも劣らない", example: "Her skill is second to none.", exampleJa: "彼女の腕前は何にも劣らない。" },
  { level: "high3", phrase: "once in a while", emoji: "🕐", meaning: "ときどき", example: "I call him once in a while.", exampleJa: "私はときどき彼に電話する。" },
  { level: "high3", phrase: "in a row", emoji: "📶", meaning: "連続して", example: "She won three times in a row.", exampleJa: "彼女は3回連続で勝った。" },
];

// レベルの定義（表示名・順序）
const LEVELS = [
  { id: "junior", name: "中学レベル", desc: "基礎・よく使う表現", emoji: "🌱" },
  { id: "high12", name: "高校1・2年", desc: "標準的な英熟語", emoji: "🌿" },
  { id: "high3", name: "高校3年・大学1年", desc: "入試・応用レベル", emoji: "🌳" },
];

// ===== 似た意味の別解（ニュアンスが近い言い換えも正解にする）=====
// 同じグループ内の語は、互いに「別解」として受け入れられる。
// （グループ内の語のうち、実際の熟語(phrase)に一致するものへ accept が付く。
//   熟語でない語＝単なる受け入れワードとして使える）
const SYNONYM_GROUPS = [
  ["for example", "for instance"],
  ["look for", "search for"],
  ["a lot of", "lots of", "plenty of", "many", "much", "a number of"],
  ["give up", "give in", "quit"],
  ["in spite of", "regardless of", "despite"],
  ["as a result", "therefore", "consequently", "as a consequence"],
  ["take care of", "look after", "care for"],
  ["throw away", "get rid of", "discard", "dispose of"],
  ["show up", "turn up", "appear"],
  ["come across", "run into", "bump into"],
  ["put off", "postpone", "delay"],
  ["deal with", "cope with", "handle"],
  ["take place", "happen", "occur"],
  ["by the way", "incidentally"],
  ["of course", "certainly", "sure", "naturally"],
  ["in fact", "as a matter of fact", "actually", "in reality"],
  ["for good", "forever", "permanently"],
  ["once in a while", "sometimes", "occasionally", "now and then", "from time to time"],
  ["once in a blue moon", "rarely", "seldom", "hardly ever"],
  ["calm down", "relax", "settle down"],
  ["figure out", "work out", "make out"],
  ["look up to", "respect", "admire"],
  ["look down on", "despise", "scorn"],
  ["make up your mind", "make a decision", "decide"],
  ["get along with", "get on with"],
  ["in addition to", "as well as", "besides"],
  ["instead of", "rather than", "in place of"],
  ["according to", "based on"],
  ["bring up", "raise", "mention"],
  ["call off", "cancel"],
  ["carry on", "keep on", "go on", "continue"],
  ["catch up", "keep up"],
  ["cut down", "reduce", "cut back"],
  ["depend on", "count on", "rely on"],
  ["focus on", "concentrate on"],
  ["hand in", "submit", "turn in"],
  ["hang out", "spend time"],
  ["hold on", "hang on", "wait"],
  ["look into", "investigate", "examine"],
  ["move on", "proceed"],
  ["pass away", "die", "pass on"],
  ["pay attention", "concentrate"],
  ["put up with", "tolerate", "stand", "endure", "bear"],
  ["take after", "resemble"],
  ["take over", "take control"],
  ["turn down", "reject", "refuse", "decline"],
  ["all of a sudden", "suddenly", "all at once"],
  ["on purpose", "deliberately", "intentionally"],
  ["take part in", "participate in", "join"],
  ["as soon as possible", "right away", "asap", "immediately", "at once"],
  ["make up for", "compensate for"],
  ["take advantage of", "exploit", "make use of"],
  ["come up with", "think of", "devise"],
  ["point out", "indicate"],
  ["turn out", "end up", "wind up", "prove to be"],
  ["find out", "discover", "learn"],
  ["look like", "resemble", "seem like"],
];

const ACCEPTED_ALTERNATIVES = {};
SYNONYM_GROUPS.forEach((group) => {
  group.forEach((phrase) => {
    ACCEPTED_ALTERNATIVES[phrase] = group.filter((other) => other !== phrase);
  });
});
IDIOMS.forEach((idiom) => {
  if (ACCEPTED_ALTERNATIVES[idiom.phrase]) {
    idiom.accept = ACCEPTED_ALTERNATIVES[idiom.phrase];
  }
});

// ブラウザでは window のグローバル、Node（テスト）では module.exports として使える
if (typeof module !== "undefined" && module.exports) {
  module.exports = { IDIOMS, LEVELS };
}
