/**
 * 語源データ（接頭辞・語根）。
 *   ORIGIN_PREFIXES … 単語の頭につく接頭辞（in-, un-, uni- など）
 *   ORIGIN_ROOTS    … 接頭辞の次に来る語根（mini, just など）
 * それぞれ form（つづり）・meaning（意味）・examples（例単語）を持つ。
 */
const ORIGIN_PREFIXES = [
  { form: "ad-", also: "ap-, at-, ac-, as-, ob-", meaning: "〜の方へ・〜の方を", examples: ["administer", "advocate", "admonish", "adjust", "appoint", "attend", "accurate", "achieve", "accept", "assign", "observe", "occur", "offend"] },
  { form: "con-, com-, co-", meaning: "共に", examples: ["conform", "contract", "congress", "confine", "consent", "concrete", "compete", "conquest", "conclude", "commemorate", "compel", "corrupt"] },
  { form: "de-", meaning: "離れて・下に", examples: ["decide", "debate", "depart", "depress", "detour", "deficit"] },
  { form: "sub-", also: "sup-, sus-", meaning: "下に", examples: ["substitute", "substance", "subordinate", "submit", "supply", "suspend", "sustain"] },
  { form: "sur-, super-", meaning: "上に・超えて", examples: ["survey", "survive", "surpass", "supervise", "superfluous"] },
  { form: "ex-", also: "e-, em-", meaning: "外に", examples: ["exceed", "exist", "expatriate", "evacuate", "emancipate"] },
  { form: "pro-, pre-, for-", meaning: "前に・前で", examples: ["promote", "project", "prospect", "prolong", "protest", "produce", "program", "prohibit", "prefer", "predict", "preside", "pregnant", "perfect", "forecast"] },
  { form: "re-", meaning: "再び・元に・後ろに", examples: ["retreat", "restrict", "resemble", "result", "reinforce", "revolve", "remodel", "rely", "relieve"] },
  { form: "in-, im-, en-", also: "em-", meaning: "中に・上に", examples: ["inspire", "incline", "indigenous", "import", "impediment", "embarrass", "encourage", "initiate", "impose", "instruct", "invent"] },
  { form: "ab-, dis-, se-", meaning: "分離・否定・反対", examples: ["abuse", "abort", "disappear", "distinguish", "disarm", "discharge", "separate"] },
  { form: "un-, im-, in-, a-", also: "ir-", meaning: "否定（〜ない）", examples: ["apathy", "anonymous", "intangible", "infant", "immediate", "irregular", "uncertain", "uncover"] },
  { form: "mono-, uni-, bi-, du-, tri-, multi-", meaning: "数（1・2・3・たくさん）", examples: ["monotonous", "universal", "biennial", "duplicate", "trivial", "multiple"] },
];

const ORIGIN_ROOTS = [
  { form: "mini", meaning: "小さい", examples: ["administer", "minimum", "minor"] },
  { form: "voc, vok, vouch", meaning: "声・呼ぶ", examples: ["advocate", "vocal", "voice"] },
  { form: "mon", meaning: "示す・警告する", examples: ["admonish", "monitor"] },
  { form: "just, jur", meaning: "正しい・法", examples: ["adjust", "justice", "jury"] },
  { form: "point, punct", meaning: "指す・点", examples: ["appoint", "point", "punctual"] },
  { form: "tend, tens", meaning: "伸ばす・向ける", examples: ["attend", "extend", "tension"] },
  { form: "cure, care", meaning: "世話・注意", examples: ["accurate", "cure", "careful"] },
  { form: "chief, cap, cup", meaning: "頭・つかむ", examples: ["achieve", "capture", "captain"] },
  { form: "cept, ceive", meaning: "つかむ・受け取る", examples: ["accept", "receive", "concept"] },
  { form: "sign", meaning: "しるし", examples: ["assign", "signal", "signature"] },
  { form: "serve, sert", meaning: "保つ・守る・仕える", examples: ["observe", "preserve", "reserve"] },
  { form: "cur", meaning: "走る・流れる", examples: ["occur", "current", "recur"] },
  { form: "fend, fens, fest", meaning: "打つ・たたく", examples: ["offend", "defend", "defense"] },
  { form: "form", meaning: "形", examples: ["conform", "reform", "form"] },
  { form: "tract, tra", meaning: "引く", examples: ["contract", "attract", "extract"] },
  { form: "gress, grad", meaning: "行く・進む", examples: ["congress", "progress", "grade"] },
  { form: "fin", meaning: "終わる・限る", examples: ["confine", "finish", "final"] },
  { form: "sens, sent", meaning: "感じる", examples: ["consent", "sense", "sentiment"] },
  { form: "crease, cru", meaning: "増える・成長する", examples: ["concrete", "increase", "create"] },
  { form: "pet, peat", meaning: "求める", examples: ["compete", "appetite", "repeat"] },
  { form: "quest, quire", meaning: "求める", examples: ["conquest", "require", "request"] },
  { form: "clude, close", meaning: "閉じる", examples: ["conclude", "include", "close"] },
  { form: "memo, mind", meaning: "心・記憶", examples: ["commemorate", "memory", "remind"] },
  { form: "pel, peal, pul", meaning: "駆り立てる・押す", examples: ["compel", "appeal", "pulse"] },
  { form: "rupt", meaning: "崩れる・破れる", examples: ["corrupt", "interrupt", "bankrupt"] },
  { form: "cide, cise", meaning: "切る", examples: ["decide", "precise", "scissors"] },
  { form: "bat", meaning: "たたく", examples: ["debate", "combat", "battle"] },
  { form: "part", meaning: "分かれる・部分", examples: ["depart", "part", "partial"] },
  { form: "press", meaning: "押す", examples: ["depress", "express", "pressure"] },
  { form: "tour, turn, tir", meaning: "曲がる・回る", examples: ["detour", "return", "tour"] },
  { form: "fic, fac, fect", meaning: "する・作る", examples: ["deficit", "factory", "perfect"] },
  { form: "stitute, sta, stat", meaning: "立つ", examples: ["substitute", "substance", "stable"] },
  { form: "ord", meaning: "順番", examples: ["subordinate", "order", "ordinary"] },
  { form: "mit, mis", meaning: "送る", examples: ["submit", "mission", "transmit"] },
  { form: "ply, ple, pli", meaning: "満たす", examples: ["supply", "complete", "plenty"] },
  { form: "pend, pense", meaning: "つるす・はかる", examples: ["suspend", "expend", "pension"] },
  { form: "tain, ten", meaning: "保つ", examples: ["sustain", "contain", "maintain"] },
  { form: "vey, view, vis", meaning: "見る", examples: ["survey", "view", "supervise"] },
  { form: "vive, viv", meaning: "生きる", examples: ["survive", "revive", "vivid"] },
  { form: "pass, pace", meaning: "歩く・通る", examples: ["surpass", "pass", "pace"] },
  { form: "flu", meaning: "流れる", examples: ["superfluous", "fluent", "influence"] },
  { form: "ceed, cede, cess", meaning: "行く・進む", examples: ["exceed", "proceed", "success"] },
  { form: "sist, st", meaning: "立つ", examples: ["exist", "assist", "insist"] },
  { form: "patri, pater", meaning: "父", examples: ["expatriate", "patriot", "paternal"] },
  { form: "vac, void", meaning: "空・から", examples: ["evacuate", "vacant", "avoid"] },
  { form: "man, mani", meaning: "手", examples: ["emancipate", "manual", "manage"] },
  { form: "mot, mov", meaning: "動く", examples: ["promote", "motion", "move"] },
  { form: "ject, jet", meaning: "投げる", examples: ["project", "reject", "inject"] },
  { form: "spect, spic", meaning: "見る", examples: ["prospect", "inspect", "respect"] },
  { form: "long, ling", meaning: "長い", examples: ["prolong", "long", "linger"] },
  { form: "test", meaning: "証言する", examples: ["protest", "testify", "contest"] },
  { form: "duce, duct", meaning: "導く", examples: ["produce", "reduce", "introduce"] },
  { form: "gram, graph", meaning: "書く", examples: ["program", "graph", "photograph"] },
  { form: "hibit", meaning: "置く・持つ", examples: ["prohibit", "exhibit", "inhibit"] },
  { form: "fer", meaning: "運ぶ", examples: ["prefer", "transfer", "offer"] },
  { form: "dict", meaning: "言う", examples: ["predict", "dictionary", "contradict"] },
  { form: "side, sit, sed", meaning: "座る", examples: ["preside", "reside", "sit"] },
  { form: "gna, nat", meaning: "生まれる", examples: ["pregnant", "nature", "native"] },
  { form: "fect, fact", meaning: "なす・作る", examples: ["perfect", "factory", "affect"] },
  { form: "cast", meaning: "投げる", examples: ["forecast", "broadcast", "cast"] },
  { form: "treat, trait", meaning: "引く", examples: ["retreat", "treat", "trait"] },
  { form: "strict, strain, stress", meaning: "引っ張る・締める", examples: ["restrict", "strain", "stress"] },
  { form: "sem, simil", meaning: "同じ・似た", examples: ["resemble", "similar", "assemble"] },
  { form: "sult, salt", meaning: "跳ぶ・跳ねる", examples: ["result", "assault", "salmon"] },
  { form: "forc, fort", meaning: "強い", examples: ["reinforce", "force", "comfort"] },
  { form: "volve, vol", meaning: "回転する", examples: ["revolve", "involve", "evolve"] },
  { form: "mode, mod", meaning: "型・程よさ", examples: ["remodel", "model", "modern"] },
  { form: "ly, lig", meaning: "結ぶ", examples: ["rely", "ally", "oblige"] },
  { form: "lev, levi", meaning: "軽い・持ち上げる", examples: ["relieve", "elevator", "level"] },
  { form: "spir(e)", meaning: "息をする", examples: ["inspire", "respire", "spirit"] },
  { form: "clin, clim", meaning: "傾く", examples: ["incline", "decline", "climate"] },
  { form: "gen", meaning: "種・生まれる", examples: ["indigenous", "generate", "gene"] },
  { form: "port", meaning: "運ぶ・港", examples: ["import", "export", "transport"] },
  { form: "ped, pod", meaning: "足", examples: ["impediment", "pedal", "pedestrian"] },
  { form: "bar", meaning: "棒・横木", examples: ["embarrass", "barrier", "bar"] },
  { form: "cor, cord", meaning: "心", examples: ["encourage", "cordial", "record"] },
  { form: "it", meaning: "行く", examples: ["initiate", "exit", "transit"] },
  { form: "pose, pon", meaning: "置く", examples: ["impose", "propose", "component"] },
  { form: "struct", meaning: "積む・建てる", examples: ["instruct", "construct", "structure"] },
  { form: "vent, ven", meaning: "来る・行く", examples: ["invent", "prevent", "event"] },
  { form: "use, uti", meaning: "使う", examples: ["abuse", "use", "utilize"] },
  { form: "ori, orig", meaning: "生まれる・始まり", examples: ["abort", "origin", "original"] },
  { form: "par, pear", meaning: "見える", examples: ["disappear", "appear", "apparent"] },
  { form: "stinct, sting", meaning: "刺す", examples: ["distinguish", "instinct", "sting"] },
  { form: "arm", meaning: "腕・武器", examples: ["disarm", "army", "armor"] },
  { form: "car, cur", meaning: "車・走る・運ぶ", examples: ["discharge", "cargo", "career"] },
  { form: "pare, pair", meaning: "並べる・そばの", examples: ["separate", "prepare", "pair"] },
  { form: "path, pass", meaning: "感じる・痛む", examples: ["apathy", "sympathy", "passion"] },
  { form: "nom, name", meaning: "名前", examples: ["anonymous", "nominate", "name"] },
  { form: "tact, tang", meaning: "触れる", examples: ["intangible", "contact", "tangible"] },
  { form: "fa", meaning: "話す", examples: ["infant", "fable", "fame"] },
  { form: "mid, med", meaning: "中間", examples: ["immediate", "middle", "medium"] },
  { form: "reg, roy", meaning: "王・支配・正す", examples: ["irregular", "regular", "royal"] },
  { form: "cert, cri", meaning: "ふるいにかける・確かめる", examples: ["uncertain", "certain", "critic"] },
  { form: "cover", meaning: "覆う", examples: ["uncover", "cover", "discover"] },
  { form: "ton, tun", meaning: "音", examples: ["monotonous", "tone", "tune"] },
  { form: "vers(e), vert", meaning: "回る・向ける", examples: ["universal", "reverse", "convert"] },
  { form: "ann(i), enn(i)", meaning: "年", examples: ["biennial", "annual", "anniversary"] },
  { form: "ple, pli, ply, ploy", meaning: "重ねる・折る", examples: ["duplicate", "multiple", "employ"] },
  { form: "via, voy, vey", meaning: "道", examples: ["trivial", "voyage", "convey"] },
];

if (typeof module !== "undefined" && module.exports) {
  module.exports = { ORIGIN_PREFIXES, ORIGIN_ROOTS };
}
